import type { ContentQuizQuestion } from "./content-types";

export type AssociateExamQuestion = ContentQuizQuestion & { moduleId: string };

export const associateExamBank: AssociateExamQuestion[] = [
  // Databricks Intelligence Platform · 6
  {
    question: "Una empresa quiere que ETL PySpark y dashboards SQL consulten la misma copia gobernada de ventas, pero que cada carga escale de forma independiente. ¿Qué arquitectura satisface mejor el requisito?",
    options: ["Exportar un CSV distinto para cada consumidor", "Guardar una tabla Delta en object storage, gobernarla con Unity Catalog y usar compute separado", "Mantener un cluster all-purpose permanente para todas las cargas", "Replicar la tabla en el almacenamiento local de cada workspace"],
    answer: 1,
    explanation: "La separación entre almacenamiento y cómputo permite compartir una tabla Delta gobernada y dimensionar cada superficie de ejecución según su workload.",
    domain: "Databricks Intelligence Platform",
    moduleId: "m01",
  },
  {
    question: "Un pipeline necesita un init script corporativo y conectividad de red que no está disponible en serverless. ¿Qué compute debe evaluar primero el ingeniero?",
    options: ["Un SQL warehouse serverless", "Un endpoint de Delta Sharing", "Compute clásico configurado mediante una policy", "Un Git folder"],
    answer: 2,
    explanation: "Classic compute ofrece controles de runtime, inicialización y red que pueden no estar disponibles en serverless; una policy mantiene los guardrails.",
    domain: "Databricks Intelligence Platform",
    moduleId: "m02",
  },
  {
    question: "Cientos de analistas ejecutan consultas SQL cortas desde una herramienta BI y la demanda cambia durante el día. ¿Qué recurso es el más apropiado?",
    options: ["Un SQL warehouse con auto-stop y escalado", "Un cluster personal por analista", "Un pool sin clusters asociados", "Una tarea for-each de Lakeflow Jobs"],
    answer: 0,
    explanation: "Los SQL warehouses están diseñados para cargas SQL y BI concurrentes, con mecanismos específicos de escalado y parada automática.",
    domain: "Databricks Intelligence Platform",
    moduleId: "m02",
  },
  {
    question: "Un lector consulta una tabla mientras otro proceso confirma un lote Delta. ¿Qué mecanismo evita que el lector observe una escritura parcial?",
    options: ["El historial de Git", "El auto-stop del compute", "Una vista temporal", "El snapshot definido por un commit atómico del transaction log"],
    answer: 3,
    explanation: "Delta publica cambios mediante commits atómicos; cada lector resuelve un snapshot consistente del transaction log.",
    domain: "Databricks Intelligence Platform",
    moduleId: "m06",
  },
  {
    question: "Un equipo compara dos configuraciones para el mismo job. Una cuesta menos por hora, pero tarda el doble y falla más. ¿Qué métrica permite una decisión correcta?",
    options: ["Número de notebooks del workspace", "Coste por ejecución correcta que cumple el SLA", "Cantidad máxima de workers configurada", "Precio de una sola DBU sin considerar runtime"],
    answer: 1,
    explanation: "El coste debe normalizarse por resultado y SLA; el precio horario aislado no captura duración, reintentos ni infraestructura cloud.",
    domain: "Databricks Intelligence Platform",
    moduleId: "m02",
  },
  {
    question: "Una revisión de arquitectura sitúa la ejecución de transformaciones Spark dentro del plano de control. ¿Qué corrección debe hacerse?",
    options: ["Mover la ejecución al plano de cómputo y dejar configuración/orquestación en el plano de control", "Mover las tablas Delta al navegador", "Sustituir Unity Catalog por un pool", "Ejecutar Spark dentro del repositorio Git"],
    answer: 0,
    explanation: "El plano de cómputo procesa los datos; el plano de control proporciona UI, APIs, configuración y coordinación de la plataforma.",
    domain: "Databricks Intelligence Platform",
    moduleId: "m01",
  },

  // Data Ingestion and Loading · 8
  {
    question: "Cada hora llegan nuevos archivos JSON a un Volume. El equipo quiere una sentencia SQL que recuerde qué archivos ya cargó. ¿Qué opción encaja mejor?",
    options: ["INSERT OVERWRITE sin filtro", "collect y escritura local", "COPY INTO sobre una tabla gobernada", "VACUUM del directorio"],
    answer: 2,
    explanation: "COPY INTO mantiene historial de archivos procesados y ofrece una carga incremental SQL sencilla; no deduplica entidades de negocio.",
    domain: "Data Ingestion and Loading",
    moduleId: "m08",
  },
  {
    question: "Un flujo de Auto Loader recibe un campo JSON inesperado. El requisito es conservar el payload para revisarlo sin incorporarlo todavía al esquema Silver. ¿Qué configuración ayuda?",
    options: ["rescuedDataColumn", "spark.sql.shuffle.partitions", "autoBroadcastJoinThreshold", "RESTORE TABLE"],
    answer: 0,
    explanation: "La columna de rescued data conserva campos que no se ajustan al esquema para que puedan medirse y tratarse posteriormente.",
    domain: "Data Ingestion and Loading",
    moduleId: "m09",
  },
  {
    question: "Un bucket contiene decenas de millones de archivos y el listado completo se ha convertido en un cuello de botella. ¿Qué modo de descubrimiento de Auto Loader debe evaluarse?",
    options: ["Un cross join con la tabla destino", "File notification, con la configuración cloud requerida", "Un collect de nombres de archivo", "Un cluster con un único worker"],
    answer: 1,
    explanation: "Las notificaciones evitan depender de listados completos repetidos y escalan el descubrimiento, aunque requieren permisos e infraestructura del proveedor.",
    domain: "Data Ingestion and Loading",
    moduleId: "m09",
  },
  {
    question: "Existe un conector managed de Lakeflow Connect para la aplicación SaaS de origen y el equipo quiere minimizar infraestructura y mantenimiento. ¿Qué decisión es más sólida?",
    options: ["Crear primero un scraper personalizado", "Exportar manualmente CSV cada semana", "Usar JDBC aunque la fuente no lo exponga", "Evaluar el conector managed y confirmar sus capacidades de frescura y CDC"],
    answer: 3,
    explanation: "Un conector managed reduce operación, pero deben comprobarse objetos soportados, disponibilidad regional, latencia y semántica incremental.",
    domain: "Data Ingestion and Loading",
    moduleId: "m09",
  },
  {
    question: "Una lectura JDBC secuencial tarda horas y la tabla fuente posee una clave numérica uniformemente distribuida. La base admite ocho conexiones. ¿Qué cambio es apropiado?",
    options: ["Configurar partitionColumn, bounds y numPartitions=8", "Aumentar spark.sql.shuffle.partitions únicamente", "Convertir el resultado a pandas antes de leer", "Abrir una conexión por fila"],
    answer: 0,
    explanation: "La lectura JDBC particionada paraleliza rangos y numPartitions limita conexiones; los bounds dividen la lectura, no filtran registros.",
    domain: "Data Ingestion and Loading",
    moduleId: "m08",
  },
  {
    question: "Una API REST devuelve páginas y aplica rate limits. ¿Qué diseño facilita reanudar sin duplicar datos tras un error?",
    options: ["Reiniciar siempre desde la primera página y hacer append", "Guardar el token en el código", "Persistir cursor/checkpoint, usar backoff e insertar con clave idempotente", "Desactivar los códigos HTTP de error"],
    answer: 2,
    explanation: "Un cursor durable y una escritura idempotente permiten reanudar; backoff respeta límites sin ocultar fallos permanentes.",
    domain: "Data Ingestion and Loading",
    moduleId: "m08",
  },
  {
    question: "Se deben gobernar imágenes y documentos antes de extraer información tabular. ¿Qué objeto de Unity Catalog es adecuado para los archivos?",
    options: ["Un task value", "Un SQL warehouse", "Una vista temporal", "Un Volume"],
    answer: 3,
    explanation: "Unity Catalog Volumes gobierna acceso a archivos no tabulares y proporciona rutas compatibles con workloads de datos.",
    domain: "Data Ingestion and Loading",
    moduleId: "m08",
  },
  {
    question: "Una consulta Auto Loader usa un checkpoint existente. El ingeniero cambia starting options esperando releer todos los archivos históricos. ¿Qué debe tener en cuenta?",
    options: ["El checkpoint conserva progreso y las nuevas opciones no necesariamente rebobinan la consulta", "El SQL warehouse eliminará el checkpoint", "Unity Catalog recreará los archivos", "VACUUM fuerza automáticamente una recarga"],
    answer: 0,
    explanation: "El checkpoint es parte del contrato de la consulta y conserva archivos/offsets procesados; un backfill debe diseñarse explícitamente.",
    domain: "Data Ingestion and Loading",
    moduleId: "m09",
  },

  // Data Transformation and Modeling · 9
  {
    question: "Todos los pedidos deben sobrevivir aunque algunos customer_id no existan en la dimensión. ¿Qué join conserva la semántica requerida?",
    options: ["Inner join", "Left join con pedidos a la izquierda", "Left semi join", "Cross join"],
    answer: 1,
    explanation: "Un left join conserva todas las filas del dataset izquierdo y produce valores nulos para dimensiones no encontradas.",
    domain: "Data Transformation and Modeling",
    moduleId: "m04",
  },
  {
    question: "Dos DataFrames contienen las mismas columnas en orden diferente. ¿Cómo combinarlos sin intercambiar valores por posición?",
    options: ["union", "crossJoin", "unionByName", "intersect"],
    answer: 2,
    explanation: "unionByName alinea columnas por nombre; union tradicional las combina por posición y no elimina duplicados.",
    domain: "Data Transformation and Modeling",
    moduleId: "m04",
  },
  {
    question: "Cada pedido contiene un array items y se necesita una fila por elemento conservando order_id. ¿Qué patrón es apropiado?",
    options: ["Seleccionar order_id y explode_outer(items), después proyectar campos del struct", "Aplicar count al array", "Convertir toda la tabla a pandas", "Usar dropDuplicates sobre todas las columnas"],
    answer: 0,
    explanation: "explode_outer aumenta la cardinalidad por elemento y conserva el padre cuando el array es nulo o vacío; order_id mantiene el contexto.",
    domain: "Data Transformation and Modeling",
    moduleId: "m04",
  },
  {
    question: "Llegan varias versiones de un pedido y debe conservarse la más reciente, resolviendo empates con ingest_id. ¿Qué solución es determinista?",
    options: ["distinct sin orden", "groupBy de todas las columnas", "dropDuplicates(['order_id'])", "row_number sobre una window ordenada por event_ts e ingest_id descendentes"],
    answer: 3,
    explanation: "La window expresa explícitamente la prioridad y el desempate; las operaciones sin orden no garantizan qué versión sobrevive.",
    domain: "Data Transformation and Modeling",
    moduleId: "m04",
  },
  {
    question: "Un pipeline usa una UDF Python para convertir texto a minúsculas, aunque Spark dispone de lower. ¿Qué cambio es preferible?",
    options: ["Usar collect y str.lower local", "Sustituir la UDF por la función nativa lower", "Aumentar el driver", "Crear otra UDF para validar la primera"],
    answer: 1,
    explanation: "Las funciones nativas son visibles para Catalyst y evitan la serialización entre JVM y Python propia de muchas UDF.",
    domain: "Data Transformation and Modeling",
    moduleId: "m04",
  },
  {
    question: "Una columna amount contiene algunos valores no numéricos. El lote debe continuar, pero los inválidos han de medirse. ¿Qué estrategia es adecuada?",
    options: ["Rellenar todos con cero", "Eliminar la columna", "Usar try_cast y cuantificar o poner en cuarentena los null resultantes", "Aplicar VACUUM"],
    answer: 2,
    explanation: "try_cast convierte entradas válidas y devuelve null para incompatibles; la métrica o cuarentena evita ocultar la pérdida.",
    domain: "Data Transformation and Modeling",
    moduleId: "m04",
  },
  {
    question: "Después de un groupBy, Spark crea miles de tareas diminutas con gran overhead. ¿Qué configuración debe revisarse y medirse?",
    options: ["spark.sql.shuffle.partitions", "La contraseña del metastore", "El nombre del catálogo", "El TTL de Git"],
    answer: 0,
    explanation: "spark.sql.shuffle.partitions influye en el número de particiones tras shuffles SQL; debe ajustarse con tamaños y duración observados.",
    domain: "Data Transformation and Modeling",
    moduleId: "m05",
  },
  {
    question: "Una agregación Gold es costosa, se consulta cientos de veces al día y puede refrescarse de forma gestionada. ¿Qué objeto debe evaluarse?",
    options: ["Una variable de notebook", "Una vista temporal", "Una materialized view", "Un secret scope"],
    answer: 2,
    explanation: "Una materialized view conserva el resultado y gestiona su refresco, evitando recalcular toda la agregación en cada lectura.",
    domain: "Data Transformation and Modeling",
    moduleId: "m07",
  },
  {
    question: "Un registro viola una regla reparable, pero el resto del lote es válido y debe publicarse. ¿Qué tratamiento preserva trazabilidad?",
    options: ["Ignorar la regla", "Enviar el registro a cuarentena con motivo y referencia al lote", "Borrar Bronze", "Conceder ALL PRIVILEGES"],
    answer: 1,
    explanation: "La cuarentena separa los registros reparables y conserva evidencia sin detener datos válidos ni perder el original.",
    domain: "Data Transformation and Modeling",
    moduleId: "m07",
  },

  // Working with Lakeflow Jobs · 6
  {
    question: "Un workflow tiene tareas ingest_eu e ingest_us independientes y una tarea conform que necesita ambas. ¿Qué DAG maximiza paralelismo correcto?",
    options: ["conform primero", "Todas sin dependencias", "Las dos ingestas en paralelo y conform dependiente de ambas", "Una cadena ingest_eu → ingest_us → conform"],
    answer: 2,
    explanation: "Las ingestas pueden ejecutarse simultáneamente; conform debe esperar a las dos dependencias.",
    domain: "Working with Lakeflow Jobs",
    moduleId: "m10",
  },
  {
    question: "Una tarea validate produce el escalar invalid_ratio que una condición downstream debe comparar. ¿Cómo compartirlo?",
    options: ["Publicarlo con taskValues y referenciarlo desde la tarea condicional", "Serializar el DataFrame completo en un widget", "Guardar el valor en el nombre del cluster", "Usar Delta Sharing"],
    answer: 0,
    explanation: "Task values están diseñados para valores pequeños entre tareas; datasets completos deben persistirse en tablas o archivos.",
    domain: "Working with Lakeflow Jobs",
    moduleId: "m10",
  },
  {
    question: "Una tarea que hace append sin clave puede ejecutarse de nuevo tras un timeout. ¿Qué debe corregirse antes de habilitar retries automáticos?",
    options: ["Aumentar el número de dashboards", "Hacer la escritura idempotente mediante clave, partición reemplazable o MERGE", "Eliminar el timeout", "Cambiar el nombre de la tarea"],
    answer: 1,
    explanation: "Un retry puede repetir efectos; la tarea debe producir el mismo estado lógico para la misma entrada.",
    domain: "Working with Lakeflow Jobs",
    moduleId: "m10",
  },
  {
    question: "Un job debe publicar si valid_ratio ≥ 0.99 y ejecutar cuarentena en caso contrario. ¿Qué componente modela mejor la decisión?",
    options: ["Una tarea for-each sobre cada fila", "Un SQL warehouse adicional", "Una tarea If/else basada en el valor de validate", "Un pool"],
    answer: 2,
    explanation: "If/else expresa una rama de control basada en un parámetro o task value; for-each resuelve iteraciones sobre colecciones.",
    domain: "Working with Lakeflow Jobs",
    moduleId: "m10",
  },
  {
    question: "Los archivos llegan a horas impredecibles y se quieren evitar runs vacíos cada cinco minutos. ¿Qué trigger elegir?",
    options: ["Una programación cron más frecuente", "Un file arrival trigger sobre la ubicación gobernada", "Un auto-stop de 24 horas", "Un repair run periódico"],
    answer: 1,
    explanation: "El trigger dirigido por llegada inicia el Job cuando existe nueva entrada y reduce sondeos y ejecuciones sin trabajo.",
    domain: "Working with Lakeflow Jobs",
    moduleId: "m10",
  },
  {
    question: "En un DAG de diez tareas falla únicamente publish. Las nueve anteriores terminaron correctamente y son costosas. ¿Cómo recuperar con menos reproceso?",
    options: ["Eliminar el Job", "Crear otro workspace", "Reiniciar todas las tareas desde cero", "Usar un repair run desde la tarea fallida"],
    answer: 3,
    explanation: "Repair run conserva resultados satisfactorios y reejecuta tareas fallidas o seleccionadas junto con sus dependientes necesarios.",
    domain: "Working with Lakeflow Jobs",
    moduleId: "m10",
  },

  // Implementing CI/CD · 5
  {
    question: "Un desarrollador quiere depurar en VS Code mientras las operaciones Spark se ejecutan en Databricks. ¿Qué herramienta cubre este flujo?",
    options: ["Databricks Connect", "Delta Sharing", "COPY INTO", "Predictive optimization"],
    answer: 0,
    explanation: "Databricks Connect permite desarrollar desde un IDE local y enviar planes a compute remoto compatible.",
    domain: "Implementing CI/CD",
    moduleId: "m03",
  },
  {
    question: "Un cambio de notebook debe revisarse antes de llegar a main. ¿Qué secuencia refleja un flujo Git correcto?",
    options: ["Editar main y duplicar el notebook", "Crear rama, commit, push y pull request", "Exportar la tabla a Git", "Guardar un token en el notebook"],
    answer: 1,
    explanation: "Las ramas aíslan el cambio y el pull request proporciona revisión; Git folders sincroniza el código con el proveedor.",
    domain: "Implementing CI/CD",
    moduleId: "m11",
  },
  {
    question: "Antes de desplegar un Declarative Automation Bundle a test, el equipo quiere resolver variables y comprobar su esquema. ¿Qué comando usar?",
    options: ["databricks fs rm", "databricks bundle run", "databricks bundle validate -t test", "RESTORE TABLE"],
    answer: 2,
    explanation: "bundle validate comprueba y resuelve la configuración del target; deploy aplica los recursos y run los ejecuta.",
    domain: "Implementing CI/CD",
    moduleId: "m11",
  },
  {
    question: "Dev, test y prod deben usar el mismo código, pero catálogos distintos. ¿Cómo modelarlo en un Bundle?",
    options: ["Tres copias del repositorio", "Un notebook distinto por workspace", "IDs productivos hardcodeados en Python", "Una variable catalog sobrescrita por cada target"],
    answer: 3,
    explanation: "Targets y variables separan configuración del artefacto, permitiendo promocionar el mismo código validado.",
    domain: "Implementing CI/CD",
    moduleId: "m11",
  },
  {
    question: "Un Job productivo desplegado por CI no debe depender de la cuenta personal del desarrollador. ¿Qué configuración es preferible?",
    options: ["run_as con un service principal de mínimo privilegio", "Un PAT personal dentro de databricks.yml", "ALL PRIVILEGES para todos", "Ejecutar siempre desde el notebook interactivo"],
    answer: 0,
    explanation: "Una identidad de servicio estable separa despliegue y ejecución y evita fallos cuando cambia el equipo.",
    domain: "Implementing CI/CD",
    moduleId: "m11",
  },

  // Troubleshooting, Monitoring, and Optimization · 6
  {
    question: "En Spark UI, 199 tareas duran 20 segundos y una tarda 14 minutos procesando muchos más bytes. ¿Cuál es la hipótesis inicial más fuerte?",
    options: ["Falta USE SCHEMA", "Data skew en la partición lenta", "Auto-stop demasiado bajo", "Error de Git"],
    answer: 1,
    explanation: "Una cola larga con distribución extrema dentro del mismo stage apunta a una clave o partición sesgada.",
    domain: "Troubleshooting, Monitoring, and Optimization",
    moduleId: "m05",
  },
  {
    question: "Muchas tareas muestran spill a disco durante un sort y todas procesan particiones grandes. ¿Qué investigación es más pertinente?",
    options: ["Revisar tamaño de particiones, memoria de ejecución y volumen del shuffle", "Conceder SELECT al driver", "Cambiar el catálogo", "Borrar el transaction log"],
    answer: 0,
    explanation: "El spill indica que estructuras de ejecución no caben en memoria; debe correlacionarse con particiones, operadores y configuración.",
    domain: "Troubleshooting, Monitoring, and Optimization",
    moduleId: "m05",
  },
  {
    question: "Un cluster nunca alcanza el estado RUNNING, por lo que no existe ningún job de Spark. ¿Dónde debe comenzar el diagnóstico?",
    options: ["En Query Profile", "En DESCRIBE HISTORY", "En eventos de compute, policy, cuota y configuración de red", "En una window function"],
    answer: 2,
    explanation: "Si Spark no llegó a iniciar, los eventos de aprovisionamiento y configuración ofrecen la evidencia relevante.",
    domain: "Troubleshooting, Monitoring, and Optimization",
    moduleId: "m05",
  },
  {
    question: "Un notebook falla con ModuleNotFoundError solo en producción. ¿Qué debe compararse primero?",
    options: ["El color del dashboard", "Versiones y origen de las dependencias instaladas en ambos entornos", "El número de catálogos", "La retención de VACUUM"],
    answer: 1,
    explanation: "El error señala una dependencia ausente o incompatible; comparar artefacto, entorno y logs es más directo que aumentar compute.",
    domain: "Troubleshooting, Monitoring, and Optimization",
    moduleId: "m03",
  },
  {
    question: "El equipo quiere saber si la duración de un Job ha empeorado gradualmente durante un mes. ¿Qué fuente es más adecuada?",
    options: ["Una captura del último run", "El contenido del checkpoint", "El README del repositorio", "Run history o system.lakeflow.job_run_timeline"],
    answer: 3,
    explanation: "El historial de runs permite comparar duraciones y estados contra una línea base temporal.",
    domain: "Troubleshooting, Monitoring, and Optimization",
    moduleId: "m10",
  },
  {
    question: "Una tabla managed grande cambia de patrones de filtro y requiere layout flexible y mantenimiento automatizado. ¿Qué capacidades debe evaluar?",
    options: ["Liquid clustering y predictive optimization", "Más widgets", "Un cross join", "Un PAT por lector"],
    answer: 0,
    explanation: "Liquid clustering adapta claves de layout y predictive optimization puede mantener tablas managed elegibles según beneficio observado.",
    domain: "Troubleshooting, Monitoring, and Optimization",
    moduleId: "m06",
  },

  // Governance and Security · 5
  {
    question: "El grupo analysts tiene SELECT sobre main.gold.sales, pero recibe un error al resolver el objeto. ¿Qué privilegios deben comprobarse en los ancestros?",
    options: ["MODIFY y OWN", "CREATE TABLE y MANAGE", "USE CATALOG en main y USE SCHEMA en main.gold", "EXECUTE en el SQL warehouse"],
    answer: 2,
    explanation: "SELECT autoriza lectura, pero el principal también necesita recorrer catálogo y esquema mediante USE.",
    domain: "Governance and Security",
    moduleId: "m11",
  },
  {
    question: "La organización quiere que cualquier columna etiquetada como PII reciba una máscara central, incluso en tablas nuevas. ¿Qué mecanismo escala mejor?",
    options: ["Una policy ABAC basada en governed tags", "Un grant individual por columna", "Un cluster por usuario", "Copiar la tabla sin PII cada noche"],
    answer: 0,
    explanation: "ABAC aplica políticas de máscara o filtro a objetos que cumplen atributos gobernados, reduciendo configuración por tabla.",
    domain: "Governance and Security",
    moduleId: "m11",
  },
  {
    question: "El propietario ejecuta DROP TABLE sobre una external table de Unity Catalog. ¿Qué ocurre con los archivos de la ubicación externa?",
    options: ["Se convierten en managed", "Se eliminan siempre", "Se mueven al workspace", "Se conserva el almacenamiento y se elimina el registro de tabla"],
    answer: 3,
    explanation: "Unity Catalog gobierna la external table, pero el ciclo de vida de sus archivos permanece fuera de DROP TABLE.",
    domain: "Governance and Security",
    moduleId: "m06",
  },
  {
    question: "Seguridad investiga quién cambió permisos; ingeniería quiere saber qué tabla alimenta un dashboard. ¿Qué señales corresponden respectivamente?",
    options: ["Spark UI y checkpoint", "Audit logs y lineage", "Liquid clustering y Photon", "COPY INTO y VACUUM"],
    answer: 1,
    explanation: "Auditoría registra acciones de principals; lineage representa relaciones entre objetos y transformaciones.",
    domain: "Governance and Security",
    moduleId: "m11",
  },
  {
    question: "Un pipeline necesita leer una ruta S3/ADLS/GCS externa sin entregar credenciales cloud a cada usuario. ¿Qué patrón de Unity Catalog corresponde?",
    options: ["Una storage credential y una external location con permisos mínimos", "Claves pegadas en widgets", "Un token dentro de la tabla", "ALL PRIVILEGES en el workspace"],
    answer: 0,
    explanation: "La storage credential encapsula la identidad cloud y la external location asocia esa identidad con una ruta gobernada.",
    domain: "Governance and Security",
    moduleId: "m11",
  },
];
