export type GlossaryCategory =
  | "plataforma"
  | "gobierno"
  | "almacenamiento"
  | "ingesta"
  | "streaming"
  | "orquestacion"
  | "rendimiento"
  | "desarrollo"
  | "seguridad"
  | "coste";

export type GlossaryEntry = {
  id: string;
  term: string;
  aliases: string[];
  category: GlossaryCategory;
  definition: string;
  whyItMatters: string;
  related: string[];
  sourceUrl: string;
  sourceLabel: string;
  reviewedAt: string;
};

export const glossaryCategoryLabels: Record<GlossaryCategory, string> = {
  plataforma: "Plataforma",
  gobierno: "Gobierno",
  almacenamiento: "Almacenamiento",
  ingesta: "Ingesta",
  streaming: "Streaming",
  orquestacion: "Orquestacion",
  rendimiento: "Rendimiento",
  desarrollo: "Desarrollo",
  seguridad: "Seguridad",
  coste: "Coste",
};

export const glossaryEntries: GlossaryEntry[] = [
  {
    id: "account",
    term: "Account",
    aliases: ["cuenta Databricks"],
    category: "plataforma",
    definition: "Entidad de nivel superior que agrupa workspaces, usuarios, facturacion y configuracion comun de la organizacion.",
    whyItMatters: "Aclara que algunas decisiones, como identidad, Unity Catalog o facturacion, se administran por encima de un workspace concreto.",
    related: ["Workspace", "Unity Catalog", "Metastore"],
    sourceUrl: "https://docs.databricks.com/aws/en/getting-started/concepts",
    sourceLabel: "Databricks components",
    reviewedAt: "2026-07-24",
  },
  {
    id: "workspace",
    term: "Workspace",
    aliases: ["entorno de trabajo"],
    category: "plataforma",
    definition: "Despliegue de Databricks en una nube donde un equipo accede a notebooks, jobs, compute, datos y otros activos.",
    whyItMatters: "Es el contexto operativo diario; muchas rutas, permisos y recursos se interpretan dentro de un workspace.",
    related: ["Account", "Git folders", "Compute"],
    sourceUrl: "https://docs.databricks.com/aws/en/getting-started/concepts",
    sourceLabel: "Databricks components",
    reviewedAt: "2026-07-24",
  },
  {
    id: "unity-catalog",
    term: "Unity Catalog",
    aliases: ["UC"],
    category: "gobierno",
    definition: "Capa de gobierno para datos y activos de IA que centraliza catalogo, permisos, lineage, discovery y auditoria.",
    whyItMatters: "Permite aplicar control de acceso y trazabilidad de forma consistente entre workspaces y cargas de trabajo.",
    related: ["Catalog", "Schema", "Metastore", "Lineage"],
    sourceUrl: "https://docs.databricks.com/aws/en/data-governance/unity-catalog/",
    sourceLabel: "Unity Catalog documentation",
    reviewedAt: "2026-07-24",
  },
  {
    id: "metastore",
    term: "Metastore",
    aliases: ["Unity Catalog metastore"],
    category: "gobierno",
    definition: "Contenedor regional de metadatos de Unity Catalog que registra catalogos, permisos y objetos gobernados.",
    whyItMatters: "Define el limite administrativo de muchos objetos gobernados y condiciona como se comparten datos entre workspaces.",
    related: ["Unity Catalog", "Catalog", "Workspace"],
    sourceUrl: "https://docs.databricks.com/aws/en/data-governance/unity-catalog/",
    sourceLabel: "Unity Catalog documentation",
    reviewedAt: "2026-07-24",
  },
  {
    id: "catalog",
    term: "Catalog",
    aliases: ["catalogo"],
    category: "gobierno",
    definition: "Primer nivel del namespace de Unity Catalog; contiene schemas con tablas, vistas, volumenes, modelos y funciones.",
    whyItMatters: "Ordena dominios de datos y ayuda a separar productos, entornos o areas de negocio con permisos claros.",
    related: ["Schema", "Table", "Volume"],
    sourceUrl: "https://docs.databricks.com/aws/en/catalogs/",
    sourceLabel: "What are catalogs in Databricks?",
    reviewedAt: "2026-07-24",
  },
  {
    id: "schema",
    term: "Schema",
    aliases: ["database", "esquema"],
    category: "gobierno",
    definition: "Segundo nivel del namespace catalog.schema.objeto; agrupa tablas, vistas, funciones, modelos y volumenes relacionados.",
    whyItMatters: "Es la unidad habitual para organizar datos por dominio, capa medallion o entorno dentro de un catalogo.",
    related: ["Catalog", "Table", "View"],
    sourceUrl: "https://docs.databricks.com/aws/en/database-objects/schema",
    sourceLabel: "What are schemas in Databricks?",
    reviewedAt: "2026-07-24",
  },
  {
    id: "managed-table",
    term: "Managed table",
    aliases: ["tabla gestionada"],
    category: "almacenamiento",
    definition: "Tabla cuyo almacenamiento y metadatos se administran desde Databricks, normalmente como Delta Lake en ubicaciones gobernadas.",
    whyItMatters: "Reduce gestion manual de rutas y facilita permisos, optimizaciones, lineage y limpieza gobernada.",
    related: ["External table", "Delta Lake", "Unity Catalog"],
    sourceUrl: "https://docs.databricks.com/aws/en/tables/",
    sourceLabel: "Tables in Databricks",
    reviewedAt: "2026-07-24",
  },
  {
    id: "external-table",
    term: "External table",
    aliases: ["tabla externa"],
    category: "almacenamiento",
    definition: "Tabla cuyos datos residen en una ubicacion externa de cloud storage mientras Databricks gobierna sus metadatos.",
    whyItMatters: "Se usa cuando el equipo necesita conservar control explicito sobre la ruta fisica o compartir datos con otros sistemas.",
    related: ["Managed table", "External location", "Unity Catalog"],
    sourceUrl: "https://docs.databricks.com/aws/en/tables/",
    sourceLabel: "Tables in Databricks",
    reviewedAt: "2026-07-24",
  },
  {
    id: "volume",
    term: "Volume",
    aliases: ["volumen"],
    category: "almacenamiento",
    definition: "Objeto de Unity Catalog para gobernar archivos no tabulares como JSON, CSV, modelos, imagenes o artefactos.",
    whyItMatters: "Evita tratar todo como tabla y permite permisos consistentes para ficheros usados por notebooks, jobs o aplicaciones.",
    related: ["Unity Catalog", "External location", "Workspace files"],
    sourceUrl: "https://docs.databricks.com/aws/en/volumes/",
    sourceLabel: "What are Unity Catalog volumes?",
    reviewedAt: "2026-07-24",
  },
  {
    id: "delta-lake",
    term: "Delta Lake",
    aliases: ["Delta"],
    category: "almacenamiento",
    definition: "Capa de almacenamiento optimizada que extiende Parquet con log transaccional, transacciones ACID y metadatos escalables.",
    whyItMatters: "Es la base de las tablas lakehouse en Databricks y permite batch, streaming, historial y operaciones DML fiables.",
    related: ["Delta table", "Transaction log", "Time travel"],
    sourceUrl: "https://docs.databricks.com/aws/en/delta/",
    sourceLabel: "What is Delta Lake in Databricks?",
    reviewedAt: "2026-07-24",
  },
  {
    id: "delta-table",
    term: "Delta table",
    aliases: ["tabla Delta"],
    category: "almacenamiento",
    definition: "Tabla almacenada en formato Delta Lake con datos Parquet y un log que registra versiones, operaciones y metadatos.",
    whyItMatters: "Es el objeto sobre el que se aplican MERGE, OPTIMIZE, time travel, streaming reads y control de calidad.",
    related: ["Delta Lake", "MERGE", "OPTIMIZE"],
    sourceUrl: "https://docs.databricks.com/aws/en/delta/",
    sourceLabel: "What is Delta Lake in Databricks?",
    reviewedAt: "2026-07-24",
  },
  {
    id: "transaction-log",
    term: "Transaction log",
    aliases: ["_delta_log", "log de Delta"],
    category: "almacenamiento",
    definition: "Registro ordenado de commits que describe los cambios de una tabla Delta y permite reconstruir sus versiones.",
    whyItMatters: "Hace posibles las transacciones ACID, time travel, auditoria de cambios y lectura incremental fiable.",
    related: ["Delta Lake", "Time travel", "Change Data Feed"],
    sourceUrl: "https://docs.databricks.com/aws/en/delta/",
    sourceLabel: "What is Delta Lake in Databricks?",
    reviewedAt: "2026-07-24",
  },
  {
    id: "time-travel",
    term: "Time travel",
    aliases: ["viaje temporal"],
    category: "almacenamiento",
    definition: "Capacidad de consultar versiones anteriores de una tabla Delta por numero de version o marca temporal.",
    whyItMatters: "Sirve para depurar cambios, reproducir resultados, recuperar datos y explicar auditorias sin duplicar tablas.",
    related: ["Delta Lake", "Transaction log", "VACUUM"],
    sourceUrl: "https://docs.databricks.com/aws/en/delta/history",
    sourceLabel: "Work with Delta Lake table history",
    reviewedAt: "2026-07-24",
  },
  {
    id: "vacuum",
    term: "VACUUM",
    aliases: ["retencion Delta"],
    category: "almacenamiento",
    definition: "Operacion que elimina archivos de datos no referenciados por versiones vigentes de una tabla Delta.",
    whyItMatters: "Controla coste de almacenamiento, pero puede limitar time travel si se reduce demasiado la retencion.",
    related: ["Time travel", "Delta Lake", "OPTIMIZE"],
    sourceUrl: "https://docs.databricks.com/aws/en/delta/vacuum",
    sourceLabel: "Remove unused data files with vacuum",
    reviewedAt: "2026-07-24",
  },
  {
    id: "merge",
    term: "MERGE",
    aliases: ["upsert"],
    category: "almacenamiento",
    definition: "Operacion Delta para insertar, actualizar o eliminar filas de una tabla destino comparandolas con una fuente.",
    whyItMatters: "Es el patron central para upserts, sincronizacion incremental, SCD y cargas idempotentes.",
    related: ["Delta table", "Change Data Feed", "SCD"],
    sourceUrl: "https://docs.databricks.com/aws/en/delta/merge",
    sourceLabel: "Upsert into a Delta Lake table using merge",
    reviewedAt: "2026-07-24",
  },
  {
    id: "change-data-feed",
    term: "Change Data Feed",
    aliases: ["CDF"],
    category: "streaming",
    definition: "Funcion de Delta Lake que expone cambios fila a fila entre versiones de una tabla para consumo incremental.",
    whyItMatters: "Permite propagar inserts, updates y deletes sin releer toda la tabla, especialmente en pipelines CDC.",
    related: ["CDC", "Delta Lake", "MERGE"],
    sourceUrl: "https://docs.databricks.com/aws/en/delta/delta-change-data-feed",
    sourceLabel: "Use change data feed on Databricks",
    reviewedAt: "2026-07-24",
  },
  {
    id: "compute",
    term: "Compute",
    aliases: ["cluster", "classic compute"],
    category: "plataforma",
    definition: "Recursos de procesamiento que ejecutan notebooks, jobs, librerias y workloads Spark o SQL en Databricks.",
    whyItMatters: "Influye en rendimiento, coste, permisos, librerias disponibles y modo de ejecucion de cada practica.",
    related: ["Databricks Runtime", "Job cluster", "Serverless compute"],
    sourceUrl: "https://docs.databricks.com/aws/en/compute/",
    sourceLabel: "Compute",
    reviewedAt: "2026-07-24",
  },
  {
    id: "job-cluster",
    term: "Job cluster",
    aliases: ["cluster de job"],
    category: "orquestacion",
    definition: "Compute efimero creado para ejecutar una tarea o job y terminado al finalizar la carga configurada.",
    whyItMatters: "Mejora aislamiento y control de coste frente a clusters compartidos de larga vida.",
    related: ["Lakeflow Jobs", "Compute", "Task"],
    sourceUrl: "https://docs.databricks.com/aws/en/jobs/",
    sourceLabel: "Lakeflow Jobs",
    reviewedAt: "2026-07-24",
  },
  {
    id: "serverless-compute",
    term: "Serverless compute",
    aliases: ["serverless"],
    category: "plataforma",
    definition: "Modo de compute gestionado por Databricks donde la plataforma aprovisiona y escala recursos sin gestionar clusters manualmente.",
    whyItMatters: "Reduce operacion y arranque manual, pero cambia limites, coste y compatibilidad de algunas configuraciones.",
    related: ["SQL warehouse", "Lakeflow", "Compute"],
    sourceUrl: "https://docs.databricks.com/aws/en/compute/serverless/",
    sourceLabel: "Serverless compute",
    reviewedAt: "2026-07-24",
  },
  {
    id: "sql-warehouse",
    term: "SQL warehouse",
    aliases: ["warehouse", "Databricks SQL warehouse"],
    category: "plataforma",
    definition: "Compute especializado para ejecutar consultas SQL, dashboards, alertas y cargas BI sobre datos del lakehouse.",
    whyItMatters: "Separa analitica SQL de clusters generales y permite dimensionar latencia, concurrencia y coste para consumidores.",
    related: ["Databricks SQL", "Photon", "Serverless compute"],
    sourceUrl: "https://docs.databricks.com/aws/en/compute/sql-warehouse/",
    sourceLabel: "SQL warehouses",
    reviewedAt: "2026-07-24",
  },
  {
    id: "databricks-runtime",
    term: "Databricks Runtime",
    aliases: ["DBR", "Runtime"],
    category: "plataforma",
    definition: "Imagen de software que incluye Apache Spark, Delta Lake, conectores, librerias y optimizaciones de Databricks.",
    whyItMatters: "La version del runtime determina APIs, compatibilidad, rendimiento y comportamiento reproducible de notebooks y jobs.",
    related: ["Compute", "Apache Spark", "Delta Lake"],
    sourceUrl: "https://docs.databricks.com/aws/en/release-notes/runtime/",
    sourceLabel: "Databricks Runtime release notes",
    reviewedAt: "2026-07-24",
  },
  {
    id: "notebook",
    term: "Notebook",
    aliases: ["cuaderno"],
    category: "desarrollo",
    definition: "Documento interactivo que combina codigo, Markdown, visualizaciones y resultados ejecutados contra compute de Databricks.",
    whyItMatters: "Es la interfaz habitual para explorar, explicar y prototipar transformaciones antes de llevarlas a jobs o pipelines.",
    related: ["Workspace", "Git folders", "Job"],
    sourceUrl: "https://docs.databricks.com/aws/en/notebooks/",
    sourceLabel: "Databricks notebooks",
    reviewedAt: "2026-07-24",
  },
  {
    id: "git-folders",
    term: "Git folders",
    aliases: ["Repos"],
    category: "desarrollo",
    definition: "Cliente Git integrado en el workspace para versionar notebooks y archivos con repositorios remotos.",
    whyItMatters: "Conecta trabajo interactivo con revision de codigo, colaboracion y despliegues reproducibles.",
    related: ["Notebook", "Declarative Automation Bundles", "CI/CD"],
    sourceUrl: "https://docs.databricks.com/aws/en/repos/",
    sourceLabel: "Databricks Git folders",
    reviewedAt: "2026-07-24",
  },
  {
    id: "declarative-automation-bundles",
    term: "Declarative Automation Bundles",
    aliases: ["Databricks Asset Bundles", "DAB"],
    category: "desarrollo",
    definition: "Formato declarativo para describir y desplegar proyectos Databricks con codigo, metadatos, jobs, pipelines y configuracion.",
    whyItMatters: "Lleva buenas practicas de IaC, revision y CI/CD a recursos de datos y analitica.",
    related: ["Git folders", "Lakeflow Jobs", "CI/CD"],
    sourceUrl: "https://docs.databricks.com/aws/en/dev-tools/bundles/",
    sourceLabel: "What are Declarative Automation Bundles?",
    reviewedAt: "2026-07-24",
  },
  {
    id: "lakeflow-jobs",
    term: "Lakeflow Jobs",
    aliases: ["Jobs", "workflows"],
    category: "orquestacion",
    definition: "Servicio de orquestacion para ejecutar workloads de produccion compuestos por una o varias tareas con dependencias.",
    whyItMatters: "Permite programar, reintentar, encadenar y observar notebooks, scripts, SQL, pipelines y otros trabajos.",
    related: ["Task", "Job cluster", "Declarative Automation Bundles"],
    sourceUrl: "https://docs.databricks.com/aws/en/jobs/",
    sourceLabel: "Lakeflow Jobs",
    reviewedAt: "2026-07-24",
  },
  {
    id: "task",
    term: "Task",
    aliases: ["tarea"],
    category: "orquestacion",
    definition: "Unidad ejecutable dentro de un job, como un notebook, script, consulta SQL, pipeline o tarea condicional.",
    whyItMatters: "Diseñar tareas pequeñas y dependencias explicitas mejora reintentos, observabilidad y recuperacion.",
    related: ["Lakeflow Jobs", "Job cluster", "DAG"],
    sourceUrl: "https://docs.databricks.com/aws/en/jobs/",
    sourceLabel: "Lakeflow Jobs",
    reviewedAt: "2026-07-24",
  },
  {
    id: "lakeflow-pipelines",
    term: "Lakeflow Declarative Pipelines",
    aliases: ["Lakeflow pipelines", "Delta Live Tables", "DLT"],
    category: "orquestacion",
    definition: "Marco declarativo para crear pipelines ETL con tablas, vistas, dependencias, expectativas y operacion gestionada.",
    whyItMatters: "Reduce codigo de orquestacion manual y hace explicitas las relaciones y reglas de calidad del pipeline.",
    related: ["Expectations", "Streaming table", "Materialized view"],
    sourceUrl: "https://docs.databricks.com/aws/en/dlt/",
    sourceLabel: "Lakeflow Declarative Pipelines",
    reviewedAt: "2026-07-24",
  },
  {
    id: "expectations",
    term: "Expectations",
    aliases: ["expectativas"],
    category: "orquestacion",
    definition: "Reglas de calidad declaradas en Lakeflow pipelines para validar, descartar, fallar o monitorizar registros.",
    whyItMatters: "Hacen visible la calidad de datos y convierten supuestos del pipeline en comportamiento verificable.",
    related: ["Lakeflow Declarative Pipelines", "Data quality", "Quarantine"],
    sourceUrl: "https://docs.databricks.com/aws/en/dlt/expectations",
    sourceLabel: "Manage data quality with pipeline expectations",
    reviewedAt: "2026-07-24",
  },
  {
    id: "lakeflow-connect",
    term: "Lakeflow Connect",
    aliases: ["managed connectors"],
    category: "ingesta",
    definition: "Conectores gestionados para ingerir datos desde aplicaciones empresariales y bases de datos hacia el lakehouse.",
    whyItMatters: "Acelera integraciones comunes y reduce mantenimiento de conectores propios cuando el origen esta soportado.",
    related: ["Lakeflow", "Ingestion", "Unity Catalog"],
    sourceUrl: "https://docs.databricks.com/aws/en/ingestion/lakeflow-connect/",
    sourceLabel: "Managed connectors in Lakeflow Connect",
    reviewedAt: "2026-07-24",
  },
  {
    id: "auto-loader",
    term: "Auto Loader",
    aliases: ["cloudFiles"],
    category: "ingesta",
    definition: "Funcionalidad para ingerir archivos nuevos desde cloud storage de forma incremental y escalable.",
    whyItMatters: "Evita listar grandes directorios manualmente y simplifica cargas continuas de ficheros con evolucion de esquema.",
    related: ["Structured Streaming", "Checkpoint", "Bronze"],
    sourceUrl: "https://docs.databricks.com/aws/en/ingestion/cloud-object-storage/auto-loader/",
    sourceLabel: "What is Auto Loader?",
    reviewedAt: "2026-07-24",
  },
  {
    id: "copy-into",
    term: "COPY INTO",
    aliases: ["carga incremental SQL"],
    category: "ingesta",
    definition: "Comando SQL para cargar datos desde archivos hacia una tabla Delta de forma incremental e idempotente.",
    whyItMatters: "Es util para ingesta batch simple cuando no hace falta mantener una consulta streaming activa.",
    related: ["Delta table", "Auto Loader", "Ingestion"],
    sourceUrl: "https://docs.databricks.com/aws/en/sql/language-manual/delta-copy-into",
    sourceLabel: "COPY INTO",
    reviewedAt: "2026-07-24",
  },
  {
    id: "structured-streaming",
    term: "Structured Streaming",
    aliases: ["streaming Spark"],
    category: "streaming",
    definition: "API de Apache Spark para procesar flujos continuos con el mismo modelo logico que DataFrames batch.",
    whyItMatters: "Sostiene ingesta incremental, transformaciones con estado y pipelines near real time en Databricks.",
    related: ["Checkpoint", "Watermark", "Auto Loader"],
    sourceUrl: "https://docs.databricks.com/aws/en/structured-streaming/",
    sourceLabel: "Structured Streaming on Databricks",
    reviewedAt: "2026-07-24",
  },
  {
    id: "checkpoint",
    term: "Checkpoint",
    aliases: ["checkpoint location"],
    category: "streaming",
    definition: "Estado persistente que guarda progreso, offsets y metadatos necesarios para reanudar una consulta streaming.",
    whyItMatters: "Sin checkpoint estable no hay recuperacion fiable ni garantias practicas de procesamiento incremental.",
    related: ["Structured Streaming", "Auto Loader", "Stateful processing"],
    sourceUrl: "https://docs.databricks.com/aws/en/structured-streaming/checkpoints",
    sourceLabel: "Structured Streaming checkpoints",
    reviewedAt: "2026-07-24",
  },
  {
    id: "watermark",
    term: "Watermark",
    aliases: ["marca de agua"],
    category: "streaming",
    definition: "Umbral temporal que permite a Spark descartar estado antiguo y manejar datos tardios en consultas streaming.",
    whyItMatters: "Controla memoria, latencia y exactitud cuando hay ventanas, agregaciones o eventos fuera de orden.",
    related: ["Structured Streaming", "Stateful processing", "Window"],
    sourceUrl: "https://docs.databricks.com/aws/en/structured-streaming/watermarks",
    sourceLabel: "Watermarks",
    reviewedAt: "2026-07-24",
  },
  {
    id: "photon",
    term: "Photon",
    aliases: ["motor Photon"],
    category: "rendimiento",
    definition: "Motor de ejecucion vectorizado de Databricks que acelera consultas SQL y cargas compatibles sobre el lakehouse.",
    whyItMatters: "Puede reducir latencia y coste efectivo, pero conviene verificar planes y compatibilidad del workload.",
    related: ["SQL warehouse", "Query Profile", "Delta Lake"],
    sourceUrl: "https://docs.databricks.com/aws/en/runtime/photon",
    sourceLabel: "What is Photon?",
    reviewedAt: "2026-07-24",
  },
  {
    id: "optimize",
    term: "OPTIMIZE",
    aliases: ["compactacion"],
    category: "rendimiento",
    definition: "Operacion Delta que reorganiza archivos para mejorar el rendimiento de lectura, especialmente tras muchas escrituras pequenas.",
    whyItMatters: "Reduce overhead de archivos pequeños y puede combinarse con tecnicas de layout como liquid clustering.",
    related: ["Delta Lake", "Liquid clustering", "Data skipping"],
    sourceUrl: "https://docs.databricks.com/aws/en/sql/language-manual/delta-optimize",
    sourceLabel: "OPTIMIZE",
    reviewedAt: "2026-07-24",
  },
  {
    id: "liquid-clustering",
    term: "Liquid clustering",
    aliases: ["clustering liquido"],
    category: "rendimiento",
    definition: "Tecnica de layout para tablas Delta que organiza datos segun columnas de clustering sin particionamiento rigido.",
    whyItMatters: "Ayuda a acelerar filtros habituales y evita algunos problemas de particiones fijas en tablas que evolucionan.",
    related: ["OPTIMIZE", "Data skipping", "Delta Lake"],
    sourceUrl: "https://docs.databricks.com/aws/en/delta/clustering",
    sourceLabel: "Use liquid clustering for Delta tables",
    reviewedAt: "2026-07-24",
  },
  {
    id: "data-skipping",
    term: "Data skipping",
    aliases: ["saltado de datos"],
    category: "rendimiento",
    definition: "Optimizacion que usa estadisticas de archivos para no leer datos que no pueden satisfacer un filtro.",
    whyItMatters: "Explica por que el layout fisico, clustering y estadisticas afectan de forma directa al coste de consulta.",
    related: ["Liquid clustering", "OPTIMIZE", "Query Profile"],
    sourceUrl: "https://docs.databricks.com/aws/en/delta/data-skipping",
    sourceLabel: "Data skipping for Delta Lake",
    reviewedAt: "2026-07-24",
  },
  {
    id: "query-profile",
    term: "Query Profile",
    aliases: ["perfil de consulta"],
    category: "rendimiento",
    definition: "Vista de diagnostico que muestra el plan y metricas de ejecucion de una consulta en Databricks SQL.",
    whyItMatters: "Permite detectar cuellos de botella, scans innecesarios, shuffles, skew y oportunidades de optimizacion.",
    related: ["SQL warehouse", "Photon", "Data skipping"],
    sourceUrl: "https://docs.databricks.com/aws/en/sql/user/queries/query-profile",
    sourceLabel: "Query profile",
    reviewedAt: "2026-07-24",
  },
  {
    id: "system-tables",
    term: "System tables",
    aliases: ["tablas de sistema"],
    category: "gobierno",
    definition: "Tablas gobernadas por Databricks que exponen datos operativos de auditoria, facturacion, lineage y uso.",
    whyItMatters: "Son la base para observabilidad, FinOps, seguridad y analisis de actividad sin exportar logs manualmente.",
    related: ["Unity Catalog", "Audit logs", "DBU"],
    sourceUrl: "https://docs.databricks.com/aws/en/admin/system-tables/",
    sourceLabel: "System tables",
    reviewedAt: "2026-07-24",
  },
  {
    id: "service-principal",
    term: "Service principal",
    aliases: ["principal de servicio"],
    category: "seguridad",
    definition: "Identidad no humana usada por jobs, automatizaciones, aplicaciones y procesos CI/CD para acceder a Databricks.",
    whyItMatters: "Evita automatizar con credenciales personales y facilita permisos minimos, rotacion y auditoria.",
    related: ["OAuth", "PAT", "Lakeflow Jobs"],
    sourceUrl: "https://docs.databricks.com/aws/en/getting-started/concepts",
    sourceLabel: "Databricks components",
    reviewedAt: "2026-07-24",
  },
  {
    id: "personal-access-token",
    term: "Personal access token",
    aliases: ["PAT"],
    category: "seguridad",
    definition: "Token usado para autenticar llamadas a APIs y herramientas; Databricks lo considera un mecanismo heredado en varios flujos.",
    whyItMatters: "Debe tratarse como secreto, rotarse y sustituirse por OAuth o identidades de servicio cuando sea posible.",
    related: ["Service principal", "OAuth", "Secret"],
    sourceUrl: "https://docs.databricks.com/aws/en/getting-started/concepts",
    sourceLabel: "Databricks components",
    reviewedAt: "2026-07-24",
  },
  {
    id: "secret-scope",
    term: "Secret scope",
    aliases: ["secrets"],
    category: "seguridad",
    definition: "Contenedor para almacenar secretos y referenciarlos desde notebooks o jobs sin escribirlos en codigo.",
    whyItMatters: "Reduce exposicion accidental de tokens, contrasenas y cadenas de conexion en notebooks, logs o repositorios.",
    related: ["PAT", "Service principal", "Job"],
    sourceUrl: "https://docs.databricks.com/aws/en/security/secrets/",
    sourceLabel: "Secret management",
    reviewedAt: "2026-07-24",
  },
  {
    id: "dbu",
    term: "DBU",
    aliases: ["Databricks Unit"],
    category: "coste",
    definition: "Unidad de procesamiento usada por Databricks para medir y facturar capacidad consumida por determinados recursos.",
    whyItMatters: "Permite comparar coste entre tipos de compute, workloads y configuraciones junto al coste de infraestructura cloud.",
    related: ["Compute", "SQL warehouse", "System tables"],
    sourceUrl: "https://docs.databricks.com/aws/en/getting-started/concepts",
    sourceLabel: "Databricks components",
    reviewedAt: "2026-07-24",
  },
  {
    id: "medallion-architecture",
    term: "Medallion architecture",
    aliases: ["arquitectura medallion"],
    category: "almacenamiento",
    definition: "Patron lakehouse que organiza datos en capas progresivas, normalmente bronze, silver y gold.",
    whyItMatters: "Ayuda a separar ingesta cruda, datos depurados y productos analiticos listos para consumo.",
    related: ["Bronze", "Silver", "Gold", "Delta Lake"],
    sourceUrl: "https://docs.databricks.com/aws/en/lakehouse/medallion",
    sourceLabel: "What is the medallion lakehouse architecture?",
    reviewedAt: "2026-07-24",
  },
  {
    id: "bronze-silver-gold",
    term: "Bronze, Silver y Gold",
    aliases: ["capas medallion"],
    category: "almacenamiento",
    definition: "Capas logicas donde bronze conserva datos de origen, silver depura y conforma, y gold publica modelos de consumo.",
    whyItMatters: "Da vocabulario comun para discutir calidad, contratos, consumidores y responsabilidades de cada tabla.",
    related: ["Medallion architecture", "Delta table", "Data quality"],
    sourceUrl: "https://docs.databricks.com/aws/en/lakehouse/medallion",
    sourceLabel: "What is the medallion lakehouse architecture?",
    reviewedAt: "2026-07-24",
  },
];

export function glossaryEntriesByInitial() {
  return glossaryEntries.reduce<Record<string, GlossaryEntry[]>>((groups, entry) => {
    const initial = entry.term[0]?.toLocaleUpperCase("es") ?? "#";
    groups[initial] = [...(groups[initial] ?? []), entry];
    return groups;
  }, {});
}
