import type { GuideCellSeed } from "../../builder";

export const azureIngestionNotebookGuidePart1 = [
  {"sourceIndex":5,"sourceDigest":"9e2001dd1c6bf72400750d960b69c539563c1d0fb897811a274b24e6a78f4d40","points":[{"title":"Avanza por la arquitectura medallion: Bronze Layer - Raw Data Ingestion","what":"La celda materializa una etapa Bronze, Silver o Gold. El foco observable es \u00abBronze Layer - Raw Data Ingestion\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"medallion","status":"current"}]},
  {"sourceIndex":6,"sourceDigest":"be51ac9b96e4272ef3ce890a09b8422bc4b150fdad7db33360fa17ba9d3725b8","points":[{"title":"Avanza por la arquitectura medallion: Add metadata columns","what":"La celda materializa una etapa Bronze, Silver o Gold mediante `spark.sql`, `Create Bronze`, `df_bronze`. El foco observable es \u00abAdd metadata columns\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque sobrescribe el destino.","topic":"medallion","status":"risky"}]},
  {"sourceIndex":7,"sourceDigest":"df210040a177874e0c8900fe2bbd1210aa227e355306a093225c2cabd93e251f","points":[{"title":"Avanza por la arquitectura medallion: %sql","what":"La celda materializa una etapa Bronze, Silver o Gold mediante `%sql`, `SELECT`. El foco observable es \u00ab%sql\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"medallion","status":"current"}]},
  {"sourceIndex":8,"sourceDigest":"3305f5cd32d39f8ef5d8bb91438fbdb09090cbcab11619fb11ff30a950dcf35a","points":[{"title":"Avanza por la arquitectura medallion: Silver Layer - Data Cleansing & Standardization","what":"La celda materializa una etapa Bronze, Silver o Gold. El foco observable es \u00abSilver Layer - Data Cleansing & Standardization\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"medallion","status":"current"}]},
  {"sourceIndex":9,"sourceDigest":"967542dc608508f8a1c6844c93f3a2112c357d097deec477b3cdd945d3949517","points":[{"title":"Avanza por la arquitectura medallion: Read from Bronze and apply quality rules","what":"La celda materializa una etapa Bronze, Silver o Gold mediante `spark.table`, `df_from_bronze`, `df_silver`, `bronze_count`. El foco observable es \u00abRead from Bronze and apply quality rules\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"medallion","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
