import type { GuideCellSeed } from "../../builder";

export const azureFederationNotebookGuidePart2 = [
  {"sourceIndex":10,"sourceDigest":"575cd2c7a349ed4cc3cb224402e614f8d7c59fddac9c1db65ade99e1ac813363","points":[{"title":"Opera sobre Delta: def generate subscriptions(n=5000)","what":"La celda modifica o consulta estado transaccional Delta mediante `spark.createDataFrame`, `subscriptions`, `start_date`, `days`. El foco observable es \u00abdef generate subscriptions(n=5000)\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque sobrescribe el destino.","topic":"delta","status":"risky"}]},
  {"sourceIndex":11,"sourceDigest":"b847c5d0939c69062b119aae1d5ae1ebfea9815f66980ec4a07da4e98fb55624","points":[{"title":"Orienta la lectura: Revenue Table","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abRevenue Table\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":12,"sourceDigest":"8479c652986de84c2e42d19f76fe9d2823adc0b7b18f75be73410e1bb36b6ada","points":[{"title":"Opera sobre Delta: def generate revenue(n=20000)","what":"La celda modifica o consulta estado transaccional Delta mediante `spark.createDataFrame`, `revenue`, `invoice_date`, `days`. El foco observable es \u00abdef generate revenue(n=20000)\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque sobrescribe el destino.","topic":"delta","status":"risky"}]},
  {"sourceIndex":13,"sourceDigest":"97c026c9e292a85765d63aaa7a87d1541380f6d15f2f806dc6a1ce040c0918bf","points":[{"title":"Observa cambios con CDF: Enable Change Data Feed","what":"La celda habilita o consume el registro incremental de cambios. El foco observable es \u00abEnable Change Data Feed\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdf","status":"current"}]},
  {"sourceIndex":14,"sourceDigest":"50a6a1d7305f29dbc7a4d4ea1e8b72da9b7573bf5e66b9013c8556c2bbd50aeb","points":[{"title":"Observa cambios con CDF: Enable Change Data Feed on all tables","what":"La celda habilita o consume el registro incremental de cambios mediante `spark.sql`, `ALTER TABLE`, `tables`, `table_full`. El foco observable es \u00abEnable Change Data Feed on all tables\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdf","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
