import type { GuideCellSeed } from "../../builder";

export const azureIngestionNotebookGuidePart0 = [
  {"sourceIndex":0,"sourceDigest":"324e512b6d559cd7c8159b2815142c21baa18528599f7ddfe43d68bd57603064","points":[{"title":"Avanza por la arquitectura medallion: 03 - Medallion Architecture Implementation","what":"La celda materializa una etapa Bronze, Silver o Gold. El foco observable es \u00ab03 - Medallion Architecture Implementation\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"medallion","status":"current"}]},
  {"sourceIndex":1,"sourceDigest":"adf1b991f148399b09e9e4981bbdd986aebca51b182a2fccd07b97153c10aab0","points":[{"title":"Orienta la lectura: Setup","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abSetup\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":2,"sourceDigest":"b4f8cdae2b6a74dc80f9777860ca0e5cf24fbb940033e77873ce1e17671781d1","points":[{"title":"Avanza por la arquitectura medallion: Use the workspace catalog","what":"La celda materializa una etapa Bronze, Silver o Gold mediante `spark.sql`, `Create schemas`, `CREATE SCHEMA IF`, `catalog_name`. El foco observable es \u00abUse the workspace catalog\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"medallion","status":"demo-only"}]},
  {"sourceIndex":3,"sourceDigest":"5f299b93447349946efb4e703fc9a7ea81f501a323452c3cae4eb7fd0fc9a88a","points":[{"title":"Orienta la lectura: Generate Sample Raw Data (Simulating Source Systems)","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abGenerate Sample Raw Data (Simulating Source Systems)\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"orientation","status":"demo-only"}]},
  {"sourceIndex":4,"sourceDigest":"2b3518b9701f94b0d8666303b07621ee80871715e56cedd92f0c4fa06b27684b","points":[{"title":"Avanza por la arquitectura medallion: Generate raw transaction data","what":"La celda materializa una etapa Bronze, Silver o Gold mediante `%Y-`, `%m-`, `%d`, `%H`. El foco observable es \u00abGenerate raw transaction data\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"medallion","status":"demo-only"}]},
] as const satisfies readonly GuideCellSeed[];
