import type { GuideCellSeed } from "../../builder";

export const azureFederationNotebookGuidePart1 = [
  {"sourceIndex":5,"sourceDigest":"5669a3dc6a6022b40ff37391019f27ae3ae2e774f28b7215651f11cc17efbf51","points":[{"title":"Orienta la lectura: Customers Table","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abCustomers Table\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":6,"sourceDigest":"09abb2bc5d932a46fd83e39ca8585eab45348f86167a987e9d39eec09652e9ef","points":[{"title":"Opera sobre Delta: Generate customer data","what":"La celda modifica o consulta estado transaccional Delta mediante `spark.createDataFrame`, `regions`, `countries`, `customers`. El foco observable es \u00abGenerate customer data\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque sobrescribe el destino.","topic":"delta","status":"risky"}]},
  {"sourceIndex":7,"sourceDigest":"0e03ab0bb4a5e5b0466efb45bdf1a26132dcf8f6ad25df0b41ff20e576c5c6dd","points":[{"title":"Orienta la lectura: Products Table","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abProducts Table\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":8,"sourceDigest":"aa1c27a63c86fc4d00af5454da47bd3afb0c1caed432c8c8b5bef3ffc6c4559c","points":[{"title":"Opera sobre Delta: products = [","what":"La celda modifica o consulta estado transaccional Delta mediante `spark.createDataFrame`, `products`, `product_schema`, `df_products`. El foco observable es \u00abproducts = [\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque sobrescribe el destino.","topic":"delta","status":"risky"}]},
  {"sourceIndex":9,"sourceDigest":"02f8eccdc493dcc743298115e26e988edfab1ecda9729b4ffbd6c9253d072666","points":[{"title":"Orienta la lectura: Subscriptions Table","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abSubscriptions Table\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
