import type { GuideCellSeed } from "../../builder";

export const azureGovernanceNotebookGuidePart0 = [
  {"sourceIndex":0,"sourceDigest":"b5996e312a6511023c8f04c698fe4b5fb81a0f1593413f5a3e30bf540f8fac82","points":[{"title":"Registra linaje y clasificaci\u00f3n: 03 - Lineage and Classification","what":"La celda conecta metadatos, clasificaci\u00f3n y dependencias. El foco observable es \u00ab03 - Lineage and Classification\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"lineage","status":"demo-only"}]},
  {"sourceIndex":1,"sourceDigest":"550f7df2b9a9643091a3c5176e2dbefdf43ec1dbb686dc79df6b9cbc7d4732ed","points":[{"title":"Orienta la lectura: Install Dependencies","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abInstall Dependencies\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":2,"sourceDigest":"14ccbc2ad938154351622535b3aff61c7aab083b594c672d4bbe787e41fb3917","points":[{"title":"Registra linaje y clasificaci\u00f3n: %pip install azure-identity azure-purview-catalog pyapacheatlas","what":"La celda conecta metadatos, clasificaci\u00f3n y dependencias mediante `%pip`, `dbutils.library.restartPython`. El foco observable es \u00ab%pip install azure-identity azure-purview-catalog pyapacheatlas\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"lineage","status":"current"}]},
  {"sourceIndex":3,"sourceDigest":"04adf534a41a3b70a2bdb03644f8ef81d4dc8f0959dd746be81efe86b7ba2e6c","points":[{"title":"Orienta la lectura: Initialize Clients","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abInitialize Clients\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":4,"sourceDigest":"088eb05810f37f72d83d9bbbab11e11c93b43eaee7adc55151988dfb0cda863d","points":[{"title":"Protege la conexi\u00f3n: Get credentials","what":"La celda establece una conexi\u00f3n que requiere credenciales mediante `dbutils.secrets.get`, `purview_account_name`, `scope`, `key`. El foco observable es \u00abGet credentials\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque el fragmento maneja una credencial o cadena de conexi\u00f3n.","topic":"secrets","status":"risky"}]},
] as const satisfies readonly GuideCellSeed[];
