import type { GuideCellSeed } from "../../builder";

export const azureGovernanceNotebookGuidePart1 = [
  {"sourceIndex":5,"sourceDigest":"dce94f46d83a11e73f5416577c420b303aa98560295a39844fa30c69a548ca66","points":[{"title":"Registra linaje y clasificaci\u00f3n: Create Sample Tables for Lineage Demo","what":"La celda conecta metadatos, clasificaci\u00f3n y dependencias mediante `Create Sample`. El foco observable es \u00abCreate Sample Tables for Lineage Demo\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"lineage","status":"demo-only"}]},
  {"sourceIndex":6,"sourceDigest":"29cfafe087054daf67ff86b0b21eb740ec495ccc19dc9daa327efd2b17a20d8e","points":[{"title":"Registra linaje y clasificaci\u00f3n: %sql","what":"La celda conecta metadatos, clasificaci\u00f3n y dependencias mediante `%sql`, `create the`, `CREATE SCHEMA IF`. El foco observable es \u00ab%sql\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"lineage","status":"demo-only"}]},
  {"sourceIndex":7,"sourceDigest":"2082f8cb8397849946912ab59e4928dccd8b436f422add076d815256e079f18f","points":[{"title":"Registra linaje y clasificaci\u00f3n: %sql","what":"La celda conecta metadatos, clasificaci\u00f3n y dependencias mediante `%sql`, `Create source`, `CREATE TABLE IF`, `Insert sample`. El foco observable es \u00ab%sql\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"lineage","status":"demo-only"}]},
  {"sourceIndex":8,"sourceDigest":"b5880dda4e979727443685aa483703c6abe6098268d9ecd722cc28a4ba69a518","points":[{"title":"Registra linaje y clasificaci\u00f3n: %sql","what":"La celda conecta metadatos, clasificaci\u00f3n y dependencias mediante `%sql`, `Create transformed`, `CREATE TABLE IF`, `SELECT \n    transaction_id`. El foco observable es \u00ab%sql\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"lineage","status":"demo-only"}]},
  {"sourceIndex":9,"sourceDigest":"761aa244a423b9d0fd295a4ca6e5a94ad75f9342eb2bcd5031acfbd9ab4a6777","points":[{"title":"Registra linaje y clasificaci\u00f3n: %sql","what":"La celda conecta metadatos, clasificaci\u00f3n y dependencias mediante `%sql`, `Create aggregated`, `CREATE TABLE IF`, `SELECT \n    customer_id`. El foco observable es \u00ab%sql\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"lineage","status":"demo-only"}]},
] as const satisfies readonly GuideCellSeed[];
