import type { GuideCellSeed } from "../../builder";

export const bestPracticesNotebookGuidePart0 = [
  {"sourceIndex":0,"sourceDigest":"6adff2958e0b3e6b51ea907a2214e9a3e7ea2543b472a94e0e49f0a10936d01a","points":[{"title":"Orienta la lectura: View the latest COVID-19 hospitalization data","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abView the latest COVID-19 hospitalization data\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":1,"sourceDigest":"94a19d792220cf2127e1c33da41ce575b96001ba67bc48e76c80c4539dee7147","points":[{"title":"Prepara el entorno: %load ext autoreload","what":"La celda configura dependencias y sesi\u00f3n mediante `%load_ext`, `%autoreload`. El foco observable es \u00ab%load ext autoreload\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"environment","status":"current"}]},
  {"sourceIndex":2,"sourceDigest":"b9383b24d6946623f2b681a9bf2c5215c55ff1d2ca9530f02698308013369af7","points":[{"title":"Orienta la lectura: Get and Transform data","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abGet and Transform data\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":3,"sourceDigest":"c7600deab1e6b2bb99b8116d2b1a3fc9b7c44b0cd5d2fae65a6b4aa4ec8bccde","points":[{"title":"Transforma el DataFrame: data path = 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/hospi","what":"La celda compone transformaciones declarativas mediante `data_path`. El foco observable es \u00abdata path = 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/hospi\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"dataframe","status":"current"}]},
  {"sourceIndex":4,"sourceDigest":"b9b2c39bf11e13b71b42bd71363a0c4c1785cecffe734c49e25df5599c3a0447","points":[{"title":"Inspecciona la salida: Convert from Pandas to a pyspark sql DataFrame.","what":"La celda muestra una vista acotada del resultado mediante `spark.createDataFrame`, `country`, `fillna`, `colname`. El foco observable es \u00abConvert from Pandas to a pyspark sql DataFrame.\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
] as const satisfies readonly GuideCellSeed[];
