import type { GuideCellSeed } from "../../builder";

export const crdbNotebookGuidePart1 = [
  {"sourceIndex":5,"sourceDigest":"adc5dba4fe96eff5c8f4799e942587628d9f9430eb1f86f798d16f8343ceda62","points":[{"title":"Protege la conexi\u00f3n: Import CockroachDB connection utilities","what":"La celda establece una conexi\u00f3n que requiere credenciales mediante `test`, `conn`, `cockroachdb_host`, `cockroachdb_port`. El foco observable es \u00abImport CockroachDB connection utilities\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque el fragmento maneja una credencial o cadena de conexi\u00f3n.","topic":"secrets","status":"risky"}]},
  {"sourceIndex":6,"sourceDigest":"beb26e991c60c4d1ad84ea28244fa836b8751deb64a33996c604dfa972ac3e0a","points":[{"title":"Ingiere cambios de la fuente: Import storage utilities (works with both Azure and UC Volume)","what":"La celda selecciona y materializa un modo de captura de cambios. El foco observable es \u00abImport storage utilities (works with both Azure and UC Volume)\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdc","status":"current"}]},
  {"sourceIndex":7,"sourceDigest":"e604379a0f4ce20502427ecd8f190945a57aeb9a2455fb89838244d0d829334d","points":[{"title":"Ingiere cambios de la fuente: Create table using cockroachdb ycsb.py","what":"La celda selecciona y materializa un modo de captura de cambios mediante `Create table using`, `Create table\ntry`, `conn`, `table_name`. El foco observable es \u00abCreate table using cockroachdb ycsb.py\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdc","status":"current"}]},
  {"sourceIndex":8,"sourceDigest":"e13d5778f7cef881927c93482b1a58f684488aa2f89fb089a0780c4d8d1b5d8c","points":[{"title":"Ingiere cambios de la fuente: from cockroachdb ycsb import insert ycsb snapshot with random nulls","what":"La celda selecciona y materializa un modo de captura de cambios mediante `conn`, `table_name`, `snapshot_count`, `null_probability`. El foco observable es \u00abfrom cockroachdb ycsb import insert ycsb snapshot with random nulls\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdc","status":"current"}]},
  {"sourceIndex":9,"sourceDigest":"f4265d6e5c5f88e38624a843deaa38f9d1aa64c9eab8c9d4167069455849b96a","points":[{"title":"Ingiere cambios de la fuente: from cockroachdb sql import create changefeed from config","what":"La celda selecciona y materializa un modo de captura de cambios mediante `result`. El foco observable es \u00abfrom cockroachdb sql import create changefeed from config\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdc","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
