import type { GuideCellSeed } from "../../builder";

export const crdbNotebookGuidePart4 = [
  {"sourceIndex":20,"sourceDigest":"5efcc1c22b9d4c50ad0e80a8002fab71c1db934bd0bc9c6773a24f1298a79acc","points":[{"title":"Protege la conexi\u00f3n: CLEANUP CELL 2: DROP SOURCE TABLE (CockroachDB)","what":"La celda establece una conexi\u00f3n que requiere credenciales mediante `DROP SOURCE`, `conn`, `cockroachdb_host`, `cockroachdb_port`. El foco observable es \u00abCLEANUP CELL 2: DROP SOURCE TABLE (CockroachDB)\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque el fragmento maneja una credencial o cadena de conexi\u00f3n.","topic":"secrets","status":"risky"}]},
  {"sourceIndex":21,"sourceDigest":"139dfd5fe236d00d6b927b843631386a352e2155434609228ea359894628c135","points":[{"title":"Protege la conexi\u00f3n: importlib.reload(cockroachdb azure)","what":"La celda establece una conexi\u00f3n que requiere credenciales mediante `result`, `storage_account_name`, `storage_account_key`, `container_name`. El foco observable es \u00abimportlib.reload(cockroachdb azure)\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque el fragmento maneja una credencial o cadena de conexi\u00f3n.","topic":"secrets","status":"risky"}]},
  {"sourceIndex":22,"sourceDigest":"c67463abac79228af913e1a3173965b14ca04388ebff5ae9cb5cd007bc3684a3","points":[{"title":"Limpia el laboratorio: CLEANUP CELL 3: DROP TARGET TABLE & CHECKPOINT (Databricks)","what":"La celda retira artefactos persistentes del ejercicio mediante `spark.sql`, `dbutils.fs.rm`, `DROP TARGET`, `Drop Delta`. El foco observable es \u00abCLEANUP CELL 3: DROP TARGET TABLE & CHECKPOINT (Databricks)\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque ejecuta una eliminaci\u00f3n o una operaci\u00f3n destructiva.","topic":"cleanup","status":"risky"}]},
  {"sourceIndex":23,"sourceDigest":"db5020cb60020dd4e6b28589c1e2fb7971ed97a75ced70c3ec0963039e32e0a5","points":[{"title":"Limpia el laboratorio: CLEANUP CELL 4: Complete cleanup for fresh start","what":"La celda retira artefactos persistentes del ejercicio mediante `spark.sql`, `dbutils.fs.rm`, `Drop staging`, `DROP TABLE IF`. El foco observable es \u00abCLEANUP CELL 4: Complete cleanup for fresh start\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque ejecuta una eliminaci\u00f3n o una operaci\u00f3n destructiva.","topic":"cleanup","status":"risky"}]},
  {"sourceIndex":24,"sourceDigest":"0ff3d354c3b3865adcb40d0e4f7ab921f3ddb0f9782d34bea11a9ab5a09414c4","points":[{"title":"Ingiere cambios de la fuente: Recreate the schema","what":"La celda selecciona y materializa un modo de captura de cambios mediante `spark.sql`, `CREATE SCHEMA IF`, `schemas`, `schema_names`. El foco observable es \u00abRecreate the schema\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdc","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
