import type { GuideCellSeed } from "../../builder";

export const crdbNotebookGuidePart3 = [
  {"sourceIndex":15,"sourceDigest":"cace3e1df5b3fa5131293e98b4424c9561af2ba27a6cc1b04a9ff5af739ed949","points":[{"title":"Ingiere cambios de la fuente: ALL-IN-ONE CDC DIAGNOSIS","what":"La celda selecciona y materializa un modo de captura de cambios mediante `conn`, `spark`, `config`. El foco observable es \u00abALL-IN-ONE CDC DIAGNOSIS\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"cdc","status":"demo-only"}]},
  {"sourceIndex":16,"sourceDigest":"1c3f419fe926747530c58ebabd4779d12a1f5b70351325df0be4ad12400aac64","points":[{"title":"Ingiere cambios de la fuente: Optional: Cleanup","what":"La celda selecciona y materializa un modo de captura de cambios. El foco observable es \u00abOptional: Cleanup\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdc","status":"current"}]},
  {"sourceIndex":17,"sourceDigest":"a628b5902ba0b20af4e5fcb805a9a0a56b0226c743862959e07e7f52e829cde3","points":[{"title":"Det\u00e9n la ejecuci\u00f3n antes de limpiar","what":"La celda es una barrera de lectura: enumera los objetos que las celdas de limpieza retirar\u00edan, pero no ejecuta el borrado. Confirma el inventario antes de avanzar a una operaci\u00f3n destructiva.","topic":"cleanup","status":"current"}]},
  {"sourceIndex":18,"sourceDigest":"213f9894ce99a3696c82aca31579c16e585a705b26337a5d686b4fa5a5f3d1bb","points":[{"title":"Protege la conexi\u00f3n: if conn is None","what":"La celda establece una conexi\u00f3n que requiere credenciales mediante `conn`, `cockroachdb_host`, `cockroachdb_port`, `cockroachdb_user`. El foco observable es \u00abif conn is None\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque el fragmento maneja una credencial o cadena de conexi\u00f3n.","topic":"secrets","status":"risky"}]},
  {"sourceIndex":19,"sourceDigest":"e0de0fb691c1691fcccfffbd84cb72a76ad3752da3f5a9c7ea614c2ddf9d3981","points":[{"title":"Cancela los changefeeds del laboratorio","what":"La celda localiza y cancela changefeeds de CockroachDB mediante `result`. Se marca como arriesgada porque detiene productores de cambios; confirma sus identificadores y el entorno antes de ejecutarla.","topic":"cleanup","status":"risky"}]},
] as const satisfies readonly GuideCellSeed[];
