import type { GuideCellSeed } from "../../builder";

export const crdbNotebookGuidePart2 = [
  {"sourceIndex":10,"sourceDigest":"b5265546a0e17ad0892288fab52a7d5db6abbe11d78b4fda08729eec238796d0","points":[{"title":"Protege la conexi\u00f3n: Ensure schema in storage (run before first ingestion)","what":"La celda establece una conexi\u00f3n que requiere credenciales. El foco observable es \u00abEnsure schema in storage (run before first ingestion)\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque el fragmento maneja una credencial o cadena de conexi\u00f3n.","topic":"secrets","status":"risky"}]},
  {"sourceIndex":11,"sourceDigest":"af5d2277411fc13eaa47d7897b18295ceeacf178a76d325a028759e49177845b","points":[{"title":"Protege la conexi\u00f3n: Ensure schema file exists in storage (Azure or UC Volume) before autoloader runs.","what":"La celda establece una conexi\u00f3n que requiere credenciales. El foco observable es \u00abEnsure schema file exists in storage (Azure or UC Volume) before autoloader runs.\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque el fragmento maneja una credencial o cadena de conexi\u00f3n.","topic":"secrets","status":"risky"}]},
  {"sourceIndex":12,"sourceDigest":"e3aa91df18dec573b13a6d4a48f622a97176d6c71dc7fa0d6fd91e195e221f52","points":[{"title":"Ingiere cambios de la fuente: Capture baseline file count BEFORE generating CDC events","what":"La celda selecciona y materializa un modo de captura de cambios mediante `UPDATE will`, `result_before`, `config`, `spark`. El foco observable es \u00abCapture baseline file count BEFORE generating CDC events\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdc","status":"current"}]},
  {"sourceIndex":13,"sourceDigest":"00b13f7b13fffe92dbef1884ce141cb705157f41fc640ba13033c7dabd7611c2","points":[{"title":"Protege la conexi\u00f3n: Use the unified storage function to check for files (works with both Azure and UC Volume)","what":"La celda establece una conexi\u00f3n que requiere credenciales mediante `result`, `config`, `spark`, `verbose`. El foco observable es \u00abUse the unified storage function to check for files (works with both Azure and UC Volume)\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque el fragmento maneja una credencial o cadena de conexi\u00f3n.","topic":"secrets","status":"risky"}]},
  {"sourceIndex":14,"sourceDigest":"153c33462b0a66012f06f9e109055be6481b6dd2d4d4697f75e94f61deaeb94a","points":[{"title":"Ingiere cambios de la fuente: Import CDC ingestion functions from cockroachdb autoload.py","what":"La celda selecciona y materializa un modo de captura de cambios mediante `query.awaitTermination`, `Select function`, `MERGE logic`, `DELETE processed`. El foco observable es \u00abImport CDC ingestion functions from cockroachdb autoload.py\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdc","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
