import type { GuideCellSeed } from "../../builder";

export const crdbNotebookGuidePart0 = [
  {"sourceIndex":0,"sourceDigest":"b21bb51ec6973a16e5dbd5da39cbb3949bfd84d3725535ade68aaaa66ed1ba91","points":[{"title":"Ingiere cambios de la fuente: Stream CockroachDB CDC to Databricks (Azure)","what":"La celda selecciona y materializa un modo de captura de cambios. El foco observable es \u00abStream CockroachDB CDC to Databricks (Azure)\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"cdc","status":"demo-only"}]},
  {"sourceIndex":1,"sourceDigest":"4849c74ce5ab69089f29f254eeecc56aa5a7df14eadb962550e1582d894ae8bf","points":[{"title":"Ingiere cambios de la fuente: CDC Mode Selection","what":"La celda selecciona y materializa un modo de captura de cambios mediante `MERGE logic`, `DELETE removes`, `UPDATE modifies`, `split_column_families`. El foco observable es \u00abCDC Mode Selection\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdc","status":"current"}]},
  {"sourceIndex":2,"sourceDigest":"f448986bc1c899cf160db53efe294ada44016bc2004ed571f243510284d5264f","points":[{"title":"Ingiere cambios de la fuente: %load ext autoreload","what":"La celda selecciona y materializa un modo de captura de cambios mediante `%load_ext`, `%autoreload`. El foco observable es \u00ab%load ext autoreload\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdc","status":"current"}]},
  {"sourceIndex":3,"sourceDigest":"0e3aee0ee9c33ed622aae2ee7fc060fa6f36592115c9cad2a5e3e43c2ba7cfdd","points":[{"title":"Protege la conexi\u00f3n: Configuration file config.cdc config.path (adjust as needed)","what":"La celda establece una conexi\u00f3n que requiere credenciales mediante `config_file`, `config`. El foco observable es \u00abConfiguration file config.cdc config.path (adjust as needed)\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque el fragmento maneja una credencial o cadena de conexi\u00f3n.","topic":"secrets","status":"risky"}]},
  {"sourceIndex":4,"sourceDigest":"29520abc60b61460cfe9036514b482ef464fb43edf7dbc20997f4cfc9f5ac3b9","points":[{"title":"Ingiere cambios de la fuente: %pip install pg8000 azure-storage-blob --quiet","what":"La celda selecciona y materializa un modo de captura de cambios mediante `%pip`. El foco observable es \u00ab%pip install pg8000 azure-storage-blob --quiet\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdc","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
