import type { GuideCellSeed } from "../../builder";

export const databricksExamplesNotebookGuidePart2 = [
  {"sourceIndex":10,"sourceDigest":"61337e3283abc71eb9378fc8cc51f38d840cfb6e68770499725caae76a5cd4f6","points":[{"title":"Transforma el DataFrame: geo adm list = elt all(date list=g date list, debug=False)","what":"La celda compone transformaciones declarativas mediante `geo_adm_list`, `date_list`, `debug`. El foco observable es \u00abgeo adm list = elt all(date list=g date list, debug=False)\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"dataframe","status":"current"}]},
  {"sourceIndex":11,"sourceDigest":"d3837624edb46c6092c73d36c7fcb1a486699832e98445605d998699dd6072f7","points":[{"title":"Define par\u00e1metros: latest extract date = getArgument(\"latest extract\")","what":"La celda separa valores del entorno de la l\u00f3gica mediante `latest_extract_date`, `geo_adm_last`. El foco observable es \u00ablatest extract date = getArgument(\"latest extract\")\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"parameters","status":"demo-only"}]},
  {"sourceIndex":12,"sourceDigest":"f1ba3a18878dff4f882fe20e066744ff802da0613d758cc42dee06270018d7fa","points":[{"title":"Ejecuta la l\u00f3gica SQL: Delete the table","what":"La celda declara una operaci\u00f3n SQL sobre objetos concretos mediante `spark.sql`, `Delete the`, `create the`. El foco observable es \u00abDelete the table\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"sql","status":"current"}]},
  {"sourceIndex":13,"sourceDigest":"7e2f121c9362a175fc882932583ca3f1c363a5dc43e26da91fcf5e6c02a4b7db","points":[{"title":"Transforma el DataFrame: save as table(input geo list=geo adm list, date list=g date list, debug=True)","what":"La celda compone transformaciones declarativas mediante `input_geo_list`, `date_list`, `debug`. El foco observable es \u00absave as table(input geo list=geo adm list, date list=g date list, debug=True)\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"dataframe","status":"current"}]},
  {"sourceIndex":14,"sourceDigest":"539bb9cc46afff48a52e54a2e9684a47d314758309052d4dcddc63515121f5af","points":[{"title":"Inspecciona la salida: geo all = spark.read.table(geo hierarchy table ref).filter(col(\"extract date\") == lit(late","what":"La celda muestra una vista acotada del resultado mediante `spark.read.table`, `geo_all`. El foco observable es \u00abgeo all = spark.read.table(geo hierarchy table ref).filter(col(\"extract date\") == lit(late\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
] as const satisfies readonly GuideCellSeed[];
