import type { GuideCellSeed } from "../../builder";

export const databricksExamplesNotebookGuidePart1 = [
  {"sourceIndex":5,"sourceDigest":"ff0dec6ea38f074ebe8058dbc39e1c511cace4700c7f24890b4bc15121ff53b2","points":[{"title":"Opera sobre Delta: Raw schema (without extract date)","what":"La celda modifica o consulta estado transaccional Delta mediante `spark.read.option`, `geoHierarchySchema`, `bool`, `row_list`. El foco observable es \u00abRaw schema (without extract date)\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"delta","status":"current"}]},
  {"sourceIndex":6,"sourceDigest":"a65a900c65e89bd14c39ecda49da631ade1d2d2c6cd0f57a7c04251ee735bf4a","points":[{"title":"Transforma el DataFrame: import re, datetime","what":"La celda compone transformaciones declarativas mediante `%Y-`, `%m-`, `%d`, `%Y`. El foco observable es \u00abimport re, datetime\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"dataframe","status":"current"}]},
  {"sourceIndex":7,"sourceDigest":"bbbe98166a165c96ff0724585376ac7e5beb4375dbf2611143db1da90a016444","points":[{"title":"Orienta la lectura: Extracts from the main table","what":"La celda delimita el objetivo y la secuencia descrita mediante `g_date_list_from_table`, `debug`, `g_date_list`, `g_date_list_diff`. El foco observable es \u00abExtracts from the main table\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":8,"sourceDigest":"08c460398fad15a60cf96e9363cad39658c73caf6d3a9cb5370f8b0063da46ea","points":[{"title":"Define par\u00e1metros: dbutils.widgets.removeAll()","what":"La celda separa valores del entorno de la l\u00f3gica mediante `dbutils.widgets.removeAll`. El foco observable es \u00abdbutils.widgets.removeAll()\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"parameters","status":"current"}]},
  {"sourceIndex":9,"sourceDigest":"3df1dc4ee461e23c0a47b09bf4f2f62d222c81189b4ff08b715326c40889042a","points":[{"title":"Define par\u00e1metros: ","what":"La celda separa valores del entorno de la l\u00f3gica mediante `dbutils.widgets.text`, `dbutils.widgets.dropdown`, `dbutils.widgets.multiselect`, `g_date_list_from_table_for_widget`. El foco observable es \u00ab\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"parameters","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
