import type { GuideCellSeed } from "../../builder";

export const deltaExamplesNotebookGuidePart8 = [
  {"sourceIndex":45,"sourceDigest":"6bf7b7dc776d960e39552f7773a7f28ad38e15ccdbf3450a74db8eb9ababc15e","points":[{"title":"Eval\u00faa el layout f\u00edsico: set auto compaction","what":"La celda mide o modifica la distribuci\u00f3n f\u00edsica de archivos mediante `spark.sql`, `spark.databricks.delta.autoCompact.enabled`, `enabled`. El foco observable es \u00abset auto compaction\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"optimization","status":"current"}]},
  {"sourceIndex":46,"sourceDigest":"332edbb1aeec621256c2a131acf12a4f86942555ba0c15891ab27dbddbb614f0","points":[{"title":"Opera sobre Delta: now let's write with auto-compact on","what":"La celda modifica o consulta estado transaccional Delta mediante `%time`, `df.write.format`. El foco observable es \u00abnow let's write with auto-compact on\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"delta","status":"current"}]},
  {"sourceIndex":47,"sourceDigest":"b089a040f44c8700fd7ae254e228fbbda01e6008c887f0b60258384175cb4602","points":[{"title":"Transforma el DataFrame: Let's run the query again to see how this affects performance","what":"La celda compone transformaciones declarativas. El foco observable es \u00abLet's run the query again to see how this affects performance\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"dataframe","status":"current"}]},
  {"sourceIndex":48,"sourceDigest":"cf8ddec0abc09718478770395c1dad50e0ead5093dc58fb30495edad51914c01","points":[{"title":"Opera sobre Delta: df comp = spark.read.format(\"delta\").load(\"delta/census table compact\")","what":"La celda modifica o consulta estado transaccional Delta mediante `spark.read.format`, `df_comp`. El foco observable es \u00abdf comp = spark.read.format(\"delta\").load(\"delta/census table compact\")\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"delta","status":"current"}]},
  {"sourceIndex":49,"sourceDigest":"23000e29ff96a7e7bda10b459d01d9d1f883039493c825ac29110c4f4debbc8f","points":[{"title":"Transforma el DataFrame: %%time","what":"La celda compone transformaciones declarativas mediante `%time`, `df_10th`, `education`. El foco observable es \u00ab%%time\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"dataframe","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
