import type { GuideCellSeed } from "../../builder";

export const deltaExamplesNotebookGuidePart10 = [
  {"sourceIndex":57,"sourceDigest":"f968007f699e38befaec49d093a14a77140b1e95be349bc6b21e6902b0acb812","points":[{"title":"Prepara el entorno: import pandas as pd","what":"La celda configura dependencias y sesi\u00f3n. El foco observable es \u00abimport pandas as pd\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"environment","status":"current"}]},
  {"sourceIndex":58,"sourceDigest":"7ea776291de7bb190cb1cb6936117bcbc3adb74479bf1951199ed40af89d8484","points":[{"title":"Opera sobre Delta: create base delta table","what":"La celda modifica o consulta estado transaccional Delta mediante `spark.read.csv`, `df.write.format`, `create base`, `header`. El foco observable es \u00abcreate base delta table\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"delta","status":"current"}]},
  {"sourceIndex":59,"sourceDigest":"cbec75dbf282befc6010cffe0dea4098dc8e4175c625beda0bfbc2a4c1a3fe4d","points":[{"title":"Orienta la lectura: read in all new data","what":"La celda delimita el objetivo y la secuencia descrita mediante `df_new`. El foco observable es \u00abread in all new data\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":60,"sourceDigest":"1e195db80cdf7a3afae75b1affc144a99eb47f19710a9ec7a8a36873a5b98e82","points":[{"title":"Orienta la lectura: def chunking params","what":"La celda delimita el objetivo y la secuencia descrita mediante `chunk_size`, `chunks`, `num_chunks`. El foco observable es \u00abdef chunking params\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":61,"sourceDigest":"5d0819ec2f65ad9b6ed5b49651ce8aef1a50b55964bfa6dcd6d2b10ae2d9c74a","points":[{"title":"Orienta la lectura: def chunks","what":"La celda delimita el objetivo y la secuencia descrita mediante `start`, `stop`. El foco observable es \u00abdef chunks\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"orientation","status":"demo-only"}]},
] as const satisfies readonly GuideCellSeed[];
