import type { GuideCellSeed } from "../../builder";

export const deltaCdfNotebookGuidePart2 = [
  {"sourceIndex":10,"sourceDigest":"de9d74a9aff09e927a8a75f2492bb76157c4e9e2529ae6191ee7d6c90ed5575d","points":[{"title":"Orienta la lectura: Append more data","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abAppend more data\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":11,"sourceDigest":"2fc8c6f04b9e20253dbef55ff2bd7ce9b04d4f41d3651fc518f6d6d40e3a05fb","points":[{"title":"Transforma el DataFrame: df = spark.createDataFrame([(5, \"Jack\", 18), (6, \"Nora\", 19), (7, \"Clare\", 20)]).toDF(","what":"La celda compone transformaciones declarativas mediante `spark.createDataFrame`. El foco observable es \u00abdf = spark.createDataFrame([(5, \"Jack\", 18), (6, \"Nora\", 19), (7, \"Clare\", 20)]).toDF(\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"dataframe","status":"current"}]},
  {"sourceIndex":12,"sourceDigest":"95e15ade51bb81f572e1580281a7a049629015137a6a4afa1c8d157554eebb7b","points":[{"title":"Opera sobre Delta: df.repartition(1).write.mode(\"append\").format(\"delta\").saveAsTable(\"students\")","what":"La celda modifica o consulta estado transaccional Delta mediante `df.repartition`. El foco observable es \u00abdf.repartition(1).write.mode(\"append\").format(\"delta\").saveAsTable(\"students\")\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"delta","status":"current"}]},
  {"sourceIndex":13,"sourceDigest":"8ff93cbbd1e10fd76dd6587a74190f58aebf1e8627b9f82309e6196b90d34484","points":[{"title":"Inspecciona la salida: spark.sql(\"SELECT FROM students\").show()","what":"La celda muestra una vista acotada del resultado mediante `spark.sql`, `SELECT`. El foco observable es \u00abspark.sql(\"SELECT FROM students\").show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
  {"sourceIndex":14,"sourceDigest":"1405eaa73044374431a8239514aaa8b7d134165fd83875bdade6c0c9d2e5ebe0","points":[{"title":"Observa cambios con CDF: spark.sql(\"SELECT FROM table changes('students', 0)\").show(truncate=False)","what":"La celda habilita o consume el registro incremental de cambios mediante `spark.sql`, `SELECT`, `truncate`. El foco observable es \u00abspark.sql(\"SELECT FROM table changes('students', 0)\").show(truncate=False)\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"cdf","status":"demo-only"}]},
] as const satisfies readonly GuideCellSeed[];
