import type { GuideCellSeed } from "../../builder";

export const deltaCdfNotebookGuidePart10 = [
  {"sourceIndex":50,"sourceDigest":"7348a5bf0fa9efbfd115270d51bf5f84337411fa285ab1d01f9652f5ae3636f5","points":[{"title":"Inspecciona la salida: spark.sql(\"select from cumulative purchases\").show()","what":"La celda muestra una vista acotada del resultado mediante `spark.sql`, `select`. El foco observable es \u00abspark.sql(\"select from cumulative purchases\").show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
  {"sourceIndex":51,"sourceDigest":"1fad347cc0b29399fa6eaa5a6d1ec2f63c5f100827afa8849e4ce746d5aa63a6","points":[{"title":"Transforma el DataFrame: another set of purchases","what":"La celda compone transformaciones declarativas mediante `spark.createDataFrame`. El foco observable es \u00abanother set of purchases\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"dataframe","status":"current"}]},
  {"sourceIndex":52,"sourceDigest":"6d8ae94532c73d68c762e792ee7dccbc4ed80ef461e0d433f51c2477b84729a0","points":[{"title":"Inspecciona la salida: df.show()","what":"La celda muestra una vista acotada del resultado mediante `df.show`. El foco observable es \u00abdf.show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
  {"sourceIndex":53,"sourceDigest":"f8edbc5ecfaec75ea17f9e7d86a727e15055c84ba1f8f1b858e025fc2d66c16f","points":[{"title":"Ingiere cambios de la fuente: minimally update cumulative purchases with the change data feed","what":"La celda selecciona y materializa un modo de captura de cambios mediante `spark.read.format`, `update cumulative_purchases`, `cdf`. El foco observable es \u00abminimally update cumulative purchases with the change data feed\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdc","status":"current"}]},
  {"sourceIndex":54,"sourceDigest":"23b7810aa53683b24739f8a0d28f828f48de1a7804d0b0e7a17905ef82a66d07","points":[{"title":"Inspecciona la salida: cdf.show()","what":"La celda muestra una vista acotada del resultado. El foco observable es \u00abcdf.show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
] as const satisfies readonly GuideCellSeed[];
