import type { GuideCellSeed } from "../../builder";

export const deltaCreateTableNotebookGuidePart6 = [
  {"sourceIndex":30,"sourceDigest":"0634f79c41d91f7bd30be24b12ffe8e8fe83789fa62e06469887bc5569b917fb","points":[{"title":"Orienta la lectura: Create Delta Lake table from CSV","what":"La celda delimita el objetivo y la secuencia descrita mediante `Create Delta`. El foco observable es \u00abCreate Delta Lake table from CSV\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":31,"sourceDigest":"731890d28a447124a199ffdca9d471d1ea5f8903d8d14cd6e53f860b7f892fab","points":[{"title":"Opera con archivos: df = spark.read.option(\"header\", True).csv(\"../../data/students/students1.csv\")","what":"La celda resuelve rutas y mueve o lee datos mediante `spark.read.option`. El foco observable es \u00abdf = spark.read.option(\"header\", True).csv(\"../../data/students/students1.csv\")\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"files","status":"current"}]},
  {"sourceIndex":32,"sourceDigest":"6d8ae94532c73d68c762e792ee7dccbc4ed80ef461e0d433f51c2477b84729a0","points":[{"title":"Inspecciona la salida: df.show()","what":"La celda muestra una vista acotada del resultado mediante `df.show`. El foco observable es \u00abdf.show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
  {"sourceIndex":33,"sourceDigest":"c67c01a1fb08b8ed2c222fd07a6ca5daa19bda75827d55573526741a65798882","points":[{"title":"Opera sobre Delta: df.write.format(\"delta\").saveAsTable(\"students\")","what":"La celda modifica o consulta estado transaccional Delta mediante `df.write.format`. El foco observable es \u00abdf.write.format(\"delta\").saveAsTable(\"students\")\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"delta","status":"current"}]},
  {"sourceIndex":34,"sourceDigest":"47fe4f0bf76820bed322d573f4614fcfc24e7bcbc62bb222f0bd1f4f2a987c3b","points":[{"title":"Inspecciona la salida: spark.sql(\"SELECT from students\").show()","what":"La celda muestra una vista acotada del resultado mediante `spark.sql`, `SELECT`. El foco observable es \u00abspark.sql(\"SELECT from students\").show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
] as const satisfies readonly GuideCellSeed[];
