import type { GuideCellSeed } from "../../builder";

export const deltaCreateTableNotebookGuidePart1 = [
  {"sourceIndex":5,"sourceDigest":"09f9d90d400eba56af4f57b99234cbb20100f6fa5164ffabfdaf6eb4afb27543","points":[{"title":"Limpia el laboratorio: spark.sql(\"DROP TABLE IF EXISTS table1\").show()","what":"La celda retira artefactos persistentes del ejercicio mediante `spark.sql`, `DROP TABLE IF`. El foco observable es \u00abspark.sql(\"DROP TABLE IF EXISTS table1\").show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque ejecuta una eliminaci\u00f3n o una operaci\u00f3n destructiva.","topic":"cleanup","status":"risky"}]},
  {"sourceIndex":6,"sourceDigest":"d01e2519d5f24d7bf3033840f29eeacbc76a1d4ac344ae10630aa3b2f55c3b8d","points":[{"title":"Transforma el DataFrame: columns = [\"character\", \"franchise\"]","what":"La celda compone transformaciones declarativas mediante `spark.sparkContext.parallelize`, `columns`, `data`, `rdd`. El foco observable es \u00abcolumns = [\"character\", \"franchise\"]\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"dataframe","status":"current"}]},
  {"sourceIndex":7,"sourceDigest":"6d8ae94532c73d68c762e792ee7dccbc4ed80ef461e0d433f51c2477b84729a0","points":[{"title":"Inspecciona la salida: df.show()","what":"La celda muestra una vista acotada del resultado mediante `df.show`. El foco observable es \u00abdf.show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
  {"sourceIndex":8,"sourceDigest":"a0b41074aad35df1861386391588d777212286242f05763bbb3308243cfe6224","points":[{"title":"Opera sobre Delta: df.write.format(\"delta\").saveAsTable(\"table1\")","what":"La celda modifica o consulta estado transaccional Delta mediante `df.write.format`. El foco observable es \u00abdf.write.format(\"delta\").saveAsTable(\"table1\")\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"delta","status":"current"}]},
  {"sourceIndex":9,"sourceDigest":"035711c4471f2a70ea1e300e30b618ad9eead382014ff9a6555ee6f44a9d7854","points":[{"title":"Inspecciona la salida: spark.sql(\"DESCRIBE HISTORY table1\").select(\"version\", \"timestamp\").show(truncate=False)","what":"La celda muestra una vista acotada del resultado mediante `spark.sql`, `truncate`. El foco observable es \u00abspark.sql(\"DESCRIBE HISTORY table1\").select(\"version\", \"timestamp\").show(truncate=False)\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
] as const satisfies readonly GuideCellSeed[];
