import type { GuideCellSeed } from "../../builder";

export const deltaCdfNotebookGuidePart9 = [
  {"sourceIndex":45,"sourceDigest":"df577261d3adbb0bb04094dd4c1c73a3ba0744a5b772d9c112a0da3ec6502961","points":[{"title":"Orienta la lectura: initially populate the cumulative purchases table","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abinitially populate the cumulative purchases table\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":46,"sourceDigest":"05069ad55565313497670a86a6f33c6d982dbe101e3d6b65bab92a14f41f46a2","points":[{"title":"Transforma el DataFrame: def agg customer purchases(df)","what":"La celda compone transformaciones declarativas mediante `df.groupBy`, `F.max`, `F.sum`. El foco observable es \u00abdef agg customer purchases(df)\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"dataframe","status":"current"}]},
  {"sourceIndex":47,"sourceDigest":"fa903a4b8ae4663289946450b68acb459060ba49feed0e64f2eadcefc1d3b992","points":[{"title":"Inspecciona la salida: spark.table(\"customer purchases\").show()","what":"La celda muestra una vista acotada del resultado mediante `spark.table`. El foco observable es \u00abspark.table(\"customer purchases\").show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
  {"sourceIndex":48,"sourceDigest":"7348a5bf0fa9efbfd115270d51bf5f84337411fa285ab1d01f9652f5ae3636f5","points":[{"title":"Inspecciona la salida: spark.sql(\"select from cumulative purchases\").show()","what":"La celda muestra una vista acotada del resultado mediante `spark.sql`, `select`. El foco observable es \u00abspark.sql(\"select from cumulative purchases\").show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
  {"sourceIndex":49,"sourceDigest":"050787453257ca55eb2df3ff2d60929c52ae057e6c810a4c42944ac035eabb31","points":[{"title":"Orienta la lectura: initial write to cumulative purchases","what":"La celda delimita el objetivo y la secuencia descrita mediante `spark.table`. El foco observable es \u00abinitial write to cumulative purchases\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
