import type { GuideCellSeed } from "../../builder";

export const deltaCdfNotebookGuidePart4 = [
  {"sourceIndex":20,"sourceDigest":"aaed8cfbe3d2d704342638aed410e0ced6de516edddb75ed25d810b62531f3a4","points":[{"title":"Observa cambios con CDF: Query change data feed","what":"La celda habilita o consume el registro incremental de cambios. El foco observable es \u00abQuery change data feed\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdf","status":"current"}]},
  {"sourceIndex":21,"sourceDigest":"1405eaa73044374431a8239514aaa8b7d134165fd83875bdade6c0c9d2e5ebe0","points":[{"title":"Observa cambios con CDF: spark.sql(\"SELECT FROM table changes('students', 0)\").show(truncate=False)","what":"La celda habilita o consume el registro incremental de cambios mediante `spark.sql`, `SELECT`, `truncate`. El foco observable es \u00abspark.sql(\"SELECT FROM table changes('students', 0)\").show(truncate=False)\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"cdf","status":"demo-only"}]},
  {"sourceIndex":22,"sourceDigest":"471ba7513d5f647b7877a91bd6b9380f39d518624d99d79bd15a0d427680bb3f","points":[{"title":"Observa cambios con CDF: spark.sql(\"SELECT FROM table changes('students', 2, 3)\").show(truncate=False)","what":"La celda habilita o consume el registro incremental de cambios mediante `spark.sql`, `SELECT`, `truncate`. El foco observable es \u00abspark.sql(\"SELECT FROM table changes('students', 2, 3)\").show(truncate=False)\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"cdf","status":"demo-only"}]},
  {"sourceIndex":23,"sourceDigest":"4faabc3491fae2f89015abbf97d5f3125a07fb4244a0dd870f23bcd8bc41b1af","points":[{"title":"Limpia el laboratorio: Cleanup","what":"La celda retira artefactos persistentes del ejercicio. El foco observable es \u00abCleanup\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cleanup","status":"current"}]},
  {"sourceIndex":24,"sourceDigest":"e99c4f1fcb877cd96facb2dea475ce1f0ce627e1acbff8354c6aab528012aada","points":[{"title":"Limpia el laboratorio: spark.sql(\"DROP TABLE IF EXISTS students\")","what":"La celda retira artefactos persistentes del ejercicio mediante `spark.sql`, `DROP TABLE IF`. El foco observable es \u00abspark.sql(\"DROP TABLE IF EXISTS students\")\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque ejecuta una eliminaci\u00f3n o una operaci\u00f3n destructiva.","topic":"cleanup","status":"risky"}]},
] as const satisfies readonly GuideCellSeed[];
