import type { GuideCellSeed } from "../../builder";

export const deltaQuickstartNotebookGuidePart3 = [
  {"sourceIndex":15,"sourceDigest":"f7f00607e61d148e35fcba0ccf0459fc56cfdaead23f68bef71428156daebb9d","points":[{"title":"Opera sobre Delta: Update every even value by adding 100 to it","what":"La celda modifica o consulta estado transaccional Delta mediante `deltaTable.update`, `Update every`, `condition`, `set`. El foco observable es \u00abUpdate every even value by adding 100 to it\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"delta","status":"current"}]},
  {"sourceIndex":16,"sourceDigest":"e83ec7d0ba528863239fa98c53faea8480d3bdde6cebb8f3e7c355cc9fb21375","points":[{"title":"Opera sobre Delta: deltaTable.toDF().show()","what":"La celda modifica o consulta estado transaccional Delta mediante `deltaTable.toDF`. El foco observable es \u00abdeltaTable.toDF().show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"delta","status":"demo-only"}]},
  {"sourceIndex":17,"sourceDigest":"b59e75ffaa164dee6212fc41421a8e17997b1f3728755e8fcc68b67823662be3","points":[{"title":"Opera sobre Delta: Delete every even value","what":"La celda modifica o consulta estado transaccional Delta mediante `deltaTable.delete`, `Delete every`, `condition`. El foco observable es \u00abDelete every even value\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque ejecuta una eliminaci\u00f3n o una operaci\u00f3n destructiva.","topic":"delta","status":"risky"}]},
  {"sourceIndex":18,"sourceDigest":"e83ec7d0ba528863239fa98c53faea8480d3bdde6cebb8f3e7c355cc9fb21375","points":[{"title":"Opera sobre Delta: deltaTable.toDF().show()","what":"La celda modifica o consulta estado transaccional Delta mediante `deltaTable.toDF`. El foco observable es \u00abdeltaTable.toDF().show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"delta","status":"demo-only"}]},
  {"sourceIndex":19,"sourceDigest":"dd9cd970fba25a84248f0c53bc3b6657e9a991ef39a2f398d12e5e344c77a1f8","points":[{"title":"Opera sobre Delta: Upsert (merge) new data","what":"La celda modifica o consulta estado transaccional Delta mediante `spark.range`, `deltaTable.alias`, `newData`, `set`. El foco observable es \u00abUpsert (merge) new data\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"delta","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
