import type { GuideCellSeed } from "../../builder";

export const deltaCdfNotebookGuidePart3 = [
  {"sourceIndex":15,"sourceDigest":"684ac86587b134b83f559c93475ba2fd20c93ce280bf1e7ad696ee247e4b6b5b","points":[{"title":"Orienta la lectura: Delete rows of data","what":"La celda delimita el objetivo y la secuencia descrita mediante `Delete rows`. El foco observable es \u00abDelete rows of data\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":16,"sourceDigest":"334ac60c768b009b29e2536e224103a29800e17c314a9c01509bb96cd7f8d620","points":[{"title":"Opera sobre Delta: delta table = DeltaTable.forName(spark, \"students\")","what":"La celda modifica o consulta estado transaccional Delta mediante `DeltaTable.forName`, `delta_table`. El foco observable es \u00abdelta table = DeltaTable.forName(spark, \"students\")\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"delta","status":"current"}]},
  {"sourceIndex":17,"sourceDigest":"7151eb953ceb7382dcb1fa247ee4bfaf04551dbfcd584869ea6ba251db2b856b","points":[{"title":"Opera sobre Delta: delta table.delete(F.col(\"age\") 20)","what":"La celda modifica o consulta estado transaccional Delta mediante `F.col`. El foco observable es \u00abdelta table.delete(F.col(\"age\") 20)\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque ejecuta una eliminaci\u00f3n o una operaci\u00f3n destructiva.","topic":"delta","status":"risky"}]},
  {"sourceIndex":18,"sourceDigest":"8ff93cbbd1e10fd76dd6587a74190f58aebf1e8627b9f82309e6196b90d34484","points":[{"title":"Inspecciona la salida: spark.sql(\"SELECT FROM students\").show()","what":"La celda muestra una vista acotada del resultado mediante `spark.sql`, `SELECT`. El foco observable es \u00abspark.sql(\"SELECT FROM students\").show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
  {"sourceIndex":19,"sourceDigest":"1405eaa73044374431a8239514aaa8b7d134165fd83875bdade6c0c9d2e5ebe0","points":[{"title":"Observa cambios con CDF: spark.sql(\"SELECT FROM table changes('students', 0)\").show(truncate=False)","what":"La celda habilita o consume el registro incremental de cambios mediante `spark.sql`, `SELECT`, `truncate`. El foco observable es \u00abspark.sql(\"SELECT FROM table changes('students', 0)\").show(truncate=False)\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"cdf","status":"demo-only"}]},
] as const satisfies readonly GuideCellSeed[];
