import type { GuideCellSeed } from "../../builder";

export const deltaQuickstartNotebookGuidePart2 = [
  {"sourceIndex":10,"sourceDigest":"b128e1b84c8a2aad77dead0f10cbeb9a6e5ed3d5e0ac856046dd252aa1632780","points":[{"title":"Opera sobre Delta: data = spark.range(5, 10)","what":"La celda modifica o consulta estado transaccional Delta mediante `spark.range`, `data`. El foco observable es \u00abdata = spark.range(5, 10)\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque sobrescribe el destino.","topic":"delta","status":"risky"}]},
  {"sourceIndex":11,"sourceDigest":"efaf90ebabb5e5cf78677ad039c5d7b737d295a4707cb298eee4541e1eecafd0","points":[{"title":"Opera sobre Delta: df = spark.read.format(\"delta\").load(\"tmp/delta-table\")","what":"La celda modifica o consulta estado transaccional Delta mediante `spark.read.format`, `df.show`. El foco observable es \u00abdf = spark.read.format(\"delta\").load(\"tmp/delta-table\")\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"delta","status":"demo-only"}]},
  {"sourceIndex":12,"sourceDigest":"297c14db004a8d9adc36eb2fdbf9c3f5cb271d6a98c2d723fdfef0ebe6609d16","points":[{"title":"Orienta la lectura: Conditional update without overwrite","what":"La celda delimita el objetivo y la secuencia descrita mediante `update without`. El foco observable es \u00abConditional update without overwrite\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":13,"sourceDigest":"e9c9e3c34a04af39175f7945022b4040815542e9f16cd73ab9a1a099a6a8e14e","points":[{"title":"Prepara el entorno: from delta.tables import","what":"La celda configura dependencias y sesi\u00f3n. El foco observable es \u00abfrom delta.tables import\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"environment","status":"current"}]},
  {"sourceIndex":14,"sourceDigest":"7172e0e44d2cdc9016b0a4bc16191b8c26ffbd083d6c9a95f69b6f391dcb7fde","points":[{"title":"Opera sobre Delta: deltaTable = DeltaTable.forPath(spark, \"tmp/delta-table\")","what":"La celda modifica o consulta estado transaccional Delta mediante `DeltaTable.forPath`, `deltaTable`. El foco observable es \u00abdeltaTable = DeltaTable.forPath(spark, \"tmp/delta-table\")\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"delta","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
