import type { GuideCellSeed } from "../../builder";

export const deltaExamplesNotebookGuidePart12 = [
  {"sourceIndex":67,"sourceDigest":"f5eef6a22a636a04956b9d05caf75e3d81016b27d44e5cdfdf6d692c86fb5ee3","points":[{"title":"Eval\u00faa el layout f\u00edsico: create base delta table","what":"La celda mide o modifica la distribuci\u00f3n f\u00edsica de archivos mediante `spark.read.csv`, `df.write.format`, `create base`, `header`. El foco observable es \u00abcreate base delta table\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"optimization","status":"current"}]},
  {"sourceIndex":68,"sourceDigest":"6bf7b7dc776d960e39552f7773a7f28ad38e15ccdbf3450a74db8eb9ababc15e","points":[{"title":"Eval\u00faa el layout f\u00edsico: set auto compaction","what":"La celda mide o modifica la distribuci\u00f3n f\u00edsica de archivos mediante `spark.sql`, `spark.databricks.delta.autoCompact.enabled`, `enabled`. El foco observable es \u00abset auto compaction\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"optimization","status":"current"}]},
  {"sourceIndex":69,"sourceDigest":"e657cae698513ae20c53eaef6ba34def5d2bdfa01f03bac0f77d7bbd819808d0","points":[{"title":"Eval\u00faa el layout f\u00edsico: for i in range(num chunks)","what":"La celda mide o modifica la distribuci\u00f3n f\u00edsica de archivos mediante `spark.createDataFrame`, `df.write.format`, `pandas_df`. El foco observable es \u00abfor i in range(num chunks)\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"optimization","status":"demo-only"}]},
  {"sourceIndex":70,"sourceDigest":"338039a7b6eb48622b3d4e74e9148dab8930c075958e2574f347675d4ed89580","points":[{"title":"Eval\u00faa el layout f\u00edsico: inspect files on disk","what":"La celda mide o modifica la distribuci\u00f3n f\u00edsica de archivos mediante `education`. El foco observable es \u00abinspect files on disk\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"optimization","status":"current"}]},
  {"sourceIndex":71,"sourceDigest":"2ac9ad508ce6f03760ab3eb300ce8b47a2945d3efe8d3f370da1f212ad5e3283","points":[{"title":"Eval\u00faa el layout f\u00edsico: we see increasingly large files that are the result of stacked optimized operations","what":"La celda mide o modifica la distribuci\u00f3n f\u00edsica de archivos. El foco observable es \u00abwe see increasingly large files that are the result of stacked optimized operations\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"optimization","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
