import type { GuideCellSeed } from "../../builder";

export const deltaCreateTableNotebookGuidePart2 = [
  {"sourceIndex":10,"sourceDigest":"119d89229fcf2cb9e8c42b6375ce27950456ca64ab460b0090015e2ace7463b0","points":[{"title":"Opera sobre Delta: dt = DeltaTable.forName(spark, \"table1\")","what":"La celda modifica o consulta estado transaccional Delta mediante `DeltaTable.forName`. El foco observable es \u00abdt = DeltaTable.forName(spark, \"table1\")\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"delta","status":"current"}]},
  {"sourceIndex":11,"sourceDigest":"1298e02ebffc67999d628390b5e5380b3621f1e27783b996192010d2033c9655","points":[{"title":"Inspecciona la salida: dt.history().select(\"version\", \"timestamp\").show(truncate=False)","what":"La celda muestra una vista acotada del resultado mediante `truncate`. El foco observable es \u00abdt.history().select(\"version\", \"timestamp\").show(truncate=False)\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
  {"sourceIndex":12,"sourceDigest":"c045a1e7481bf73684ddff28b4dd2edae119c3e7682e1a751ee00ea3818de75d","points":[{"title":"Inspecciona la salida: spark.sql(\"SELECT FROM table1\").show(truncate=False)","what":"La celda muestra una vista acotada del resultado mediante `spark.sql`, `SELECT`, `truncate`. El foco observable es \u00abspark.sql(\"SELECT FROM table1\").show(truncate=False)\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
  {"sourceIndex":13,"sourceDigest":"f75455c92358c0c4fe22f66153c2da10f7ebb08a1ae611610818eb0e7270a40c","points":[{"title":"Inspecciona la salida: spark.table(\"table1\").show()","what":"La celda muestra una vista acotada del resultado mediante `spark.table`. El foco observable es \u00abspark.table(\"table1\").show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
  {"sourceIndex":14,"sourceDigest":"7b016dac4f7eb8c2ad7b009b1a58d5f345554689a0ccfd8733aca8191bf784b4","points":[{"title":"Opera sobre Delta: DeltaTable.isDeltaTable(spark, \"spark-warehouse/table1\")","what":"La celda modifica o consulta estado transaccional Delta mediante `DeltaTable.isDeltaTable`. El foco observable es \u00abDeltaTable.isDeltaTable(spark, \"spark-warehouse/table1\")\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"delta","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
