import type { GuideCellSeed } from "../../builder";

export const deltaCdfNotebookGuidePart11 = [
  {"sourceIndex":55,"sourceDigest":"65a1e311a74e47819432bf2712443ba3476fcd9d3e8d5eb99829c0eedb4c70dc","points":[{"title":"Transforma el DataFrame: new transactions = df.join(","what":"La celda compone transformaciones declarativas mediante `df.join`, `new_transactions`. El foco observable es \u00abnew transactions = df.join(\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"dataframe","status":"current"}]},
  {"sourceIndex":56,"sourceDigest":"2875f6afb6ee94267c38666adc697bf1dd2fde7566ed54cfa02f3a96fef7f73c","points":[{"title":"Inspecciona la salida: new transactions.show()","what":"La celda muestra una vista acotada del resultado. El foco observable es \u00abnew transactions.show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
  {"sourceIndex":57,"sourceDigest":"d1328d22bc188caa7552dd7277a80a04708e561c6e0cb908d6058a60d789a5f6","points":[{"title":"Transforma el DataFrame: new df = new transactions.transform(agg customer purchases)","what":"La celda compone transformaciones declarativas mediante `new_df`. El foco observable es \u00abnew df = new transactions.transform(agg customer purchases)\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"dataframe","status":"current"}]},
  {"sourceIndex":58,"sourceDigest":"cfcb47172ddff8e2fdba11055cb72f6a736b36c8cb9ab50d9ee552bfe435019c","points":[{"title":"Inspecciona la salida: new df.show()","what":"La celda muestra una vista acotada del resultado. El foco observable es \u00abnew df.show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
  {"sourceIndex":59,"sourceDigest":"db5644b1481e5558dcdb1ffeb5258e67823975961f406ace3fb09be11ceb89ad","points":[{"title":"Inspecciona la salida: spark.table(\"cumulative purchases\").show()","what":"La celda muestra una vista acotada del resultado mediante `spark.table`. El foco observable es \u00abspark.table(\"cumulative purchases\").show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
] as const satisfies readonly GuideCellSeed[];
