import type { GuideCellSeed } from "../../builder";

export const deltaCdfNotebookGuidePart0 = [
  {"sourceIndex":0,"sourceDigest":"dbf96db4521df8b64c7738b6ac9ac0aed55359fccd48d0c30910a420e08f9b7a","points":[{"title":"Observa cambios con CDF: Delta Lake Change Data Feed","what":"La celda habilita o consume el registro incremental de cambios. El foco observable es \u00abDelta Lake Change Data Feed\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdf","status":"current"}]},
  {"sourceIndex":1,"sourceDigest":"784cdf1e47748b38097d542212fd3597f8950268f7145fcbd91e1f7709a978cc","points":[{"title":"Prepara el entorno: import pyspark","what":"La celda configura dependencias y sesi\u00f3n mediante `spark.sql.extensions`, `spark.sql.catalog.spark_catalog`, `spark.sql.delta.catalog.DeltaCatalog`, `builder`. El foco observable es \u00abimport pyspark\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"environment","status":"current"}]},
  {"sourceIndex":2,"sourceDigest":"879a5009e2263804486bd53cb14413dd6d37ac7937a84658631ba4ea899c6702","points":[{"title":"Observa cambios con CDF: Create Delta table with change data feed enabled","what":"La celda habilita o consume el registro incremental de cambios mediante `Create Delta`. El foco observable es \u00abCreate Delta table with change data feed enabled\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdf","status":"current"}]},
  {"sourceIndex":3,"sourceDigest":"b30a152719f534c9742199876c78630d5613df6fed9b6d9ae5b1ec7a7defeaa9","points":[{"title":"Define par\u00e1metros: spark.conf.set(\"spark.sql.legacy.createHiveTableByDefault\", \"false\")","what":"La celda separa valores del entorno de la l\u00f3gica mediante `spark.conf.set`, `spark.sql.legacy.createHiveTableByDefault`. El foco observable es \u00abspark.conf.set(\"spark.sql.legacy.createHiveTableByDefault\", \"false\")\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"parameters","status":"current"}]},
  {"sourceIndex":4,"sourceDigest":"1cba5dba79bbfc94214f0b22164297185a3e51aebfafebec7ee496878cffaeb2","points":[{"title":"Observa cambios con CDF: spark.sql(","what":"La celda habilita o consume el registro incremental de cambios mediante `spark.sql`, `CREATE TABLE students`, `enableChangeDataFeed`. El foco observable es \u00abspark.sql(\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdf","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
