import type { GuideCellSeed } from "../../builder";

export const deltaCdfNotebookGuidePart8 = [
  {"sourceIndex":40,"sourceDigest":"312af9a0d8cbf73f0bf54e7802a59bfb6b38c9fb2d147aa28707b78990627448","points":[{"title":"Observa cambios con CDF: spark.sql(","what":"La celda habilita o consume el registro incremental de cambios mediante `spark.sql`, `CREATE TABLE IF`, `enableChangeDataFeed`. El foco observable es \u00abspark.sql(\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"cdf","status":"current"}]},
  {"sourceIndex":41,"sourceDigest":"83db4bf4769ce0f33d20df820e04e42497916920aa266d2620b4e6c72a44a5c0","points":[{"title":"Transforma el DataFrame: df = spark.createDataFrame(","what":"La celda compone transformaciones declarativas mediante `spark.createDataFrame`. El foco observable es \u00abdf = spark.createDataFrame(\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"dataframe","status":"current"}]},
  {"sourceIndex":42,"sourceDigest":"338eb97bea7dd945096a9deb1e342c71ecab6ac4233f7b0806863ff14318409c","points":[{"title":"Opera sobre Delta: df.write.mode(\"append\").format(\"delta\").saveAsTable(\"customer purchases\")","what":"La celda modifica o consulta estado transaccional Delta mediante `df.write.mode`. El foco observable es \u00abdf.write.mode(\"append\").format(\"delta\").saveAsTable(\"customer purchases\")\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"delta","status":"current"}]},
  {"sourceIndex":43,"sourceDigest":"fa903a4b8ae4663289946450b68acb459060ba49feed0e64f2eadcefc1d3b992","points":[{"title":"Inspecciona la salida: spark.table(\"customer purchases\").show()","what":"La celda muestra una vista acotada del resultado mediante `spark.table`. El foco observable es \u00abspark.table(\"customer purchases\").show()\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"visualization","status":"demo-only"}]},
  {"sourceIndex":44,"sourceDigest":"74abdd3a73a315490bcc5f668c5a8bdb066f3ceff1c31dff2a8899f0c8dce093","points":[{"title":"Ejecuta la l\u00f3gica SQL: spark.sql(","what":"La celda declara una operaci\u00f3n SQL sobre objetos concretos mediante `spark.sql`, `CREATE TABLE IF`. El foco observable es \u00abspark.sql(\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"sql","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
