import type { GuideCellSeed } from "../../builder";

export const startupErpNotebookGuidePart1 = [
  {"sourceIndex":5,"sourceDigest":"4a87ebda57944b576049fdd06bb9cb60917c649e05f21c2c13e654c766446ed5","points":[{"title":"Orienta la lectura: Helper Functions","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abHelper Functions\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":6,"sourceDigest":"a7c98db31baa589478a7a7fba7d5011b1ad5e11d5c13becd4e2f5f7423229268","points":[{"title":"Transforma el DataFrame: def generate customers(n: int) - list","what":"La celda compone transformaciones declarativas mediante `customers`, `subscription_tiers`, `locale`, `fake_locale`. El foco observable es \u00abdef generate customers(n: int) - list\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"dataframe","status":"demo-only"}]},
  {"sourceIndex":7,"sourceDigest":"f4d7340955f882431cd34f3a65f68dc2fbb6abbef4a8289714defa7f786364c7","points":[{"title":"Orienta la lectura: Generate Data","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abGenerate Data\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"orientation","status":"demo-only"}]},
  {"sourceIndex":8,"sourceDigest":"7743ab45b1f274055adf6a3d028f70fc656ce1d5fb1955b3f5104452f413ccdf","points":[{"title":"Transforma el DataFrame: print(\"Generating synthetic startup ERP data...\")","what":"La celda compone transformaciones declarativas mediante `customers`, `contacts`, `employees`, `invoices`. El foco observable es \u00abprint(\"Generating synthetic startup ERP data...\")\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"dataframe","status":"demo-only"}]},
  {"sourceIndex":9,"sourceDigest":"bf03e2d37026d1f76e91e8acacdc9a872e03d66562f1414d7a2fef1dbd75a1e0","points":[{"title":"Avanza por la arquitectura medallion: Write to Bronze Layer (Delta Tables)","what":"La celda materializa una etapa Bronze, Silver o Gold. El foco observable es \u00abWrite to Bronze Layer (Delta Tables)\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"medallion","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
