import type { GuideCellSeed } from "../../builder";

export const startupErpNotebookGuidePart2 = [
  {"sourceIndex":10,"sourceDigest":"4388b116a055c6c56cf9dc01db65780839f18d2812f4e0fb4a0068b42bf6c5d4","points":[{"title":"Avanza por la arquitectura medallion: def write to bronze(data: list, table name: str, schema: StructType = None)","what":"La celda materializa una etapa Bronze, Silver o Gold mediante `%Y`, `%m`, `%d`, `%H`. El foco observable es \u00abdef write to bronze(data: list, table name: str, schema: StructType = None)\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque sobrescribe el destino.","topic":"medallion","status":"risky"}]},
  {"sourceIndex":11,"sourceDigest":"0c2ab00913f790d4085051a0480354264dd511786d22adab75ee5b659173f2ac","points":[{"title":"Avanza por la arquitectura medallion: Write all tables","what":"La celda materializa una etapa Bronze, Silver o Gold mediante `df_customers`, `df_contacts`, `df_employees`, `df_invoices`. El foco observable es \u00abWrite all tables\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"medallion","status":"current"}]},
  {"sourceIndex":12,"sourceDigest":"10826eed9340de7a3f94e8a3efa6b3ad08b5421b898ae47d6ac7e89e5e8e3ec6","points":[{"title":"Avanza por la arquitectura medallion: Data Quality Checks (Bronze)","what":"La celda materializa una etapa Bronze, Silver o Gold. El foco observable es \u00abData Quality Checks (Bronze)\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"medallion","status":"current"}]},
  {"sourceIndex":13,"sourceDigest":"2f29c45972a293cde0d4e84fc894910dc1ba73e79263a24e7021933f7cb4d467","points":[{"title":"Avanza por la arquitectura medallion: from pyspark.sql.functions import count, countDistinct, sum as spark sum, whe\u2026","what":"La celda materializa una etapa Bronze, Silver o Gold mediante `spark.table`, `df.count`, `df.columns`, `df.select`. El foco observable es \u00abfrom pyspark.sql.functions import count, countDistinct, sum as spark sum, when, col\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"medallion","status":"current"}]},
  {"sourceIndex":14,"sourceDigest":"3f59d58f2c2ea4dd98c54775404f5be34e07107840add4c1e2d6b761e38a4be3","points":[{"title":"Atribuye uso y coste: Cost Tracking Metadata","what":"La celda calcula o prepara una atribuci\u00f3n de consumo. El foco observable es \u00abCost Tracking Metadata\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"finops","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
