import type { GuideCellSeed } from "../../builder";

export const yokawasaNotebooksNotebookGuidePart1 = [
  {"sourceIndex":5,"sourceDigest":"8bcca6e704145bbdd6de68e7d12bf27b61f0060a6a6254b9bb58439e597aa438","points":[{"title":"Integra el servicio Azure: dbutils.fs.ls(\"wasbs://mountpoint001@databrickstore.blob.core.windows.net\")","what":"La celda configura acceso a un recurso externo de Azure mediante `dbutils.fs.ls`. El foco observable es \u00abdbutils.fs.ls(\"wasbs://mountpoint001@databrickstore.blob.core.windows.net\")\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como heredada porque usa montajes o rutas WASBS; contr\u00e1stala con almacenamiento gobernado.","topic":"azure","status":"legacy"}]},
  {"sourceIndex":6,"sourceDigest":"4cf4b6aaa2bfdc95113d6016d171c9a4a919adf2a7c0f4f4b1b1c0e97415dd41","points":[{"title":"Integra el servicio Azure: 2. Mounting Azure Blob Storage container","what":"La celda configura acceso a un recurso externo de Azure. El foco observable es \u00ab2. Mounting Azure Blob Storage container\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"azure","status":"current"}]},
  {"sourceIndex":7,"sourceDigest":"a40332579e1d78bdf71dba905bd9285f7542b4cb961e820af7bc7374bd5e521a","points":[{"title":"Integra el servicio Azure: Configure to mount Azure Blob Storage container onto local dir","what":"La celda configura acceso a un recurso externo de Azure. El foco observable es \u00abConfigure to mount Azure Blob Storage container onto local dir\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"azure","status":"current"}]},
  {"sourceIndex":8,"sourceDigest":"e88147cfd3d24c45149fea31f6dcaa5833c69f9f321d959002c2458fb0872f0c","points":[{"title":"Reconoce el montaje DBFS heredado","what":"La celda usa `dbutils.fs.mount`, `source`, `mount_point` y `extra_configs`. El montaje es un patr\u00f3n heredado; contr\u00e1stalo con vol\u00famenes o ubicaciones externas gobernadas.","topic":"azure","status":"legacy"},{"title":"Controla la mutaci\u00f3n persistente del workspace","what":"`dbutils.fs.mount` crea estado compartido que sobrevive a la ejecuci\u00f3n. Se marca como arriesgada porque una fuente, punto de montaje o configuraci\u00f3n incorrectos pueden exponer datos o colisionar con otro montaje.","topic":"files","status":"risky"}]},
  {"sourceIndex":9,"sourceDigest":"b2f7803c5c8a9d2a0df6a34875a5109f23125c873580f7faed58725570c2a6bd","points":[{"title":"Orienta la lectura: List files","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abList files\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
