import type { GuideCellSeed } from "../../builder";

export const yokawasaEventhubNotebookGuidePart0 = [
  {"sourceIndex":0,"sourceDigest":"2f87bc243a2eb8ece01fe1c7b5d5dbb0ce7d4d8c345f5871bc3a5944d224c079","points":[{"title":"Procesa el flujo incremental: Streaming Sample: Azure Event Hub - Databricks","what":"La celda define una lectura o escritura incremental con estado mediante `create a`. El foco observable es \u00abStreaming Sample: Azure Event Hub - Databricks\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"streaming","status":"current"}]},
  {"sourceIndex":1,"sourceDigest":"6963fb372ce18c6884cd5bcff62c75989a7e340805c240f70c5533dda171bf30","points":[{"title":"Procesa el flujo incremental: Event Hubs Configuration","what":"La celda define una lectura o escritura incremental con estado. El foco observable es \u00abEvent Hubs Configuration\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"streaming","status":"current"}]},
  {"sourceIndex":2,"sourceDigest":"52baa28f1946fb067a54111455b991e4d06e0fffea7fa5a83f88797dbe9d8110","points":[{"title":"Protege la conexi\u00f3n: Connection String","what":"La celda establece una conexi\u00f3n que requiere credenciales mediante `Create the`, `ev_namespace`, `ev_name`, `ev_sas_key_name`. El foco observable es \u00abConnection String\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque el fragmento maneja una credencial o cadena de conexi\u00f3n.","topic":"secrets","status":"risky"}]},
  {"sourceIndex":3,"sourceDigest":"70fc3cca41f5ee4f13c85bb884b41b2fc0006692847651d51c32cfbee5078dd5","points":[{"title":"Procesa el flujo incremental: Reading Data from Event Hubs","what":"La celda define una lectura o escritura incremental con estado. El foco observable es \u00abReading Data from Event Hubs\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"streaming","status":"current"}]},
  {"sourceIndex":4,"sourceDigest":"c1090fd79e6ee5c2bf533faf03def84d22e041731971baa779868e70537c296d","points":[{"title":"Procesa el flujo incremental: Creating an Event Hubs Source for Streaming Queries","what":"La celda define una lectura o escritura incremental con estado mediante `spark.readStream.format`, `df.withColumn`, `readInStreamBody`. El foco observable es \u00abCreating an Event Hubs Source for Streaming Queries\u00bb; verifica su efecto y conserva la evidencia indicada. Se mantiene como demostraci\u00f3n: sus datos, escala o salidas no constituyen una receta de producci\u00f3n.","topic":"streaming","status":"demo-only"}]},
] as const satisfies readonly GuideCellSeed[];
