import type { GuideCellSeed } from "../../builder";

export const yokawasaNotebooksNotebookGuidePart3 = [
  {"sourceIndex":15,"sourceDigest":"ed7bb89259a06f0a04e8c77bfd59bafd51aa9128fba31f161f3b9e1ca846ed5e","points":[{"title":"Orienta la lectura: List files in local dir","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abList files in local dir\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":16,"sourceDigest":"eac8af8a19fef3ad02928605c6e2e0b4f17697cabef4cf8b99176d4c650fad57","points":[{"title":"Opera con archivos: dbutils.fs.ls(\"file:/usr/lib/\")","what":"La celda resuelve rutas y mueve o lee datos mediante `dbutils.fs.ls`. El foco observable es \u00abdbutils.fs.ls(\"file:/usr/lib/\")\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"files","status":"current"}]},
  {"sourceIndex":17,"sourceDigest":"8f92b4197f388cab4c167119bd2981da46194fcd89cbc74299dee70918fd921c","points":[{"title":"Orienta la lectura: Read json file from mounted dir using Json parser and write them into SQL table","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abRead json file from mounted dir using Json parser and write them into SQL table\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":18,"sourceDigest":"442e4215d286c03089ed5fa2eab2a5e4cb52b0036aba8f61514276b5cf7a8ffb","points":[{"title":"Limpia el laboratorio: %sql","what":"La celda retira artefactos persistentes del ejercicio mediante `%sql`, `DROP TABLE IF`, `CREATE TABLE radio_sample_data`. El foco observable es \u00ab%sql\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque ejecuta una eliminaci\u00f3n o una operaci\u00f3n destructiva.","topic":"cleanup","status":"risky"}]},
  {"sourceIndex":19,"sourceDigest":"3887857f15ce28cd98c3849b4337b75c2f147801d278b7a8f209ccda81156e02","points":[{"title":"Orienta la lectura: select from SQL table","what":"La celda delimita el objetivo y la secuencia descrita mediante `select from`. El foco observable es \u00abselect from SQL table\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
] as const satisfies readonly GuideCellSeed[];
