import type { GuideCellSeed } from "../../builder";

export const yokawasaNotebooksNotebookGuidePart2 = [
  {"sourceIndex":10,"sourceDigest":"8754a06d6dab4b67342618c10cf8c8e6a6e84f4ae8c0be4fc2947693e553a41b","points":[{"title":"Opera con archivos: dbutils.fs.ls(\"/mnt/azstorage\")","what":"La celda resuelve rutas y mueve o lee datos mediante `dbutils.fs.ls`. El foco observable es \u00abdbutils.fs.ls(\"/mnt/azstorage\")\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"files","status":"current"}]},
  {"sourceIndex":11,"sourceDigest":"1422126c80653bafbbfffef1a1d59bdaf6169d16c50e4619bc90d2dfb3d5c5f5","points":[{"title":"Orienta la lectura: Copy files to local dir","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abCopy files to local dir\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":12,"sourceDigest":"9c82cb842b6ee62b2edf90fda0b61fc56ebba85b5f640f924fe96d8c534e8b96","points":[{"title":"Opera con archivos: dbutils.fs.cp(\"/mnt/azstorage/libmecab.so\", \"file:/usr/lib/libmecab.so\")","what":"La celda resuelve rutas y mueve o lee datos mediante `dbutils.fs.cp`. El foco observable es \u00abdbutils.fs.cp(\"/mnt/azstorage/libmecab.so\", \"file:/usr/lib/libmecab.so\")\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"files","status":"current"}]},
  {"sourceIndex":13,"sourceDigest":"8475c5bdc7e5c4246b0218df26a031c435fefc77b072063ffec4441f4f2d4bee","points":[{"title":"Orienta la lectura: Remove files in local dir","what":"La celda delimita el objetivo y la secuencia descrita. El foco observable es \u00abRemove files in local dir\u00bb; verifica su efecto y conserva la evidencia indicada.","topic":"orientation","status":"current"}]},
  {"sourceIndex":14,"sourceDigest":"2dce2054b2444d4a99e742c052fffdbb53b4b211ed07177eec4eec7e83156d36","points":[{"title":"Limpia el laboratorio: dbutils.fs.rm(\"file:/usr/lib/libmecab.so\")","what":"La celda retira artefactos persistentes del ejercicio mediante `dbutils.fs.rm`. El foco observable es \u00abdbutils.fs.rm(\"file:/usr/lib/libmecab.so\")\u00bb; verifica su efecto y conserva la evidencia indicada. Se marca como arriesgada porque ejecuta una eliminaci\u00f3n o una operaci\u00f3n destructiva.","topic":"cleanup","status":"risky"}]},
] as const satisfies readonly GuideCellSeed[];
